return {
    type = "animation_editor",
    format = "json",
    version = 1,
    data = {
        nodes = {
        },
        animations = {
            {
                duration = 2.2,
                animation_keys = {
                    {
                        property_id = "position_y",
                        easing = "outsine",
                        duration = 0.4,
                        key_type = "tween",
                        node_id = "panthera",
                        end_value = -42,
                    },
                    {
                        property_id = "scale_x",
                        easing = "outback",
                        duration = 0.42,
                        key_type = "tween",
                        node_id = "text",
                        end_value = 1.3,
                        start_value = 1,
                    },
                    {
                        property_id = "scale_y",
                        easing = "outback",
                        duration = 0.42,
                        key_type = "tween",
                        node_id = "text",
                        end_value = 1.3,
                        start_value = 1,
                    },
                    {
                        property_id = "position_y",
                        easing = "outback",
                        duration = 0.42,
                        key_type = "tween",
                        node_id = "text",
                        end_value = 45,
                        start_value = 80,
                    },
                    {
                        property_id = "position_x",
                        easing = "outsine",
                        duration = 0.8,
                        key_type = "tween",
                        node_id = "panthera",
                        end_value = 75,
                    },
                    {
                        property_id = "text",
                        easing = "linear",
                        node_id = "text",
                        key_type = "trigger",
                        start_time = 0.22,
                        data = "Just",
                        start_data = "Hello",
                    },
                    {
                        property_id = "position_y",
                        easing = "outsine",
                        duration = 1.6,
                        key_type = "tween",
                        start_time = 0.4,
                        node_id = "panthera",
                        start_value = -42,
                    },
                    {
                        property_id = "scale_x",
                        easing = "outsine",
                        duration = 0.45,
                        node_id = "text",
                        key_type = "tween",
                        start_time = 0.42,
                        end_value = 1,
                        start_value = 1.3,
                    },
                    {
                        property_id = "scale_y",
                        easing = "outsine",
                        duration = 0.45,
                        node_id = "text",
                        key_type = "tween",
                        start_time = 0.42,
                        end_value = 1,
                        start_value = 1.3,
                    },
                    {
                        property_id = "position_y",
                        easing = "outsine",
                        duration = 0.45,
                        node_id = "text",
                        key_type = "tween",
                        start_time = 0.42,
                        end_value = 75,
                        start_value = 45,
                    },
                    {
                        property_id = "position_x",
                        easing = "outsine",
                        duration = 0.6,
                        node_id = "panthera",
                        key_type = "tween",
                        start_time = 0.8,
                        end_value = -65,
                        start_value = 75,
                    },
                    {
                        property_id = "text",
                        easing = "linear",
                        node_id = "text",
                        key_type = "trigger",
                        start_time = 0.87,
                        data = "Example",
                        start_data = "Just",
                    },
                    {
                        property_id = "position_x",
                        easing = "outsine",
                        duration = 0.6,
                        key_type = "tween",
                        start_time = 1.4,
                        node_id = "panthera",
                        start_value = -65,
                    },
                },
                animation_id = "default",
            },
        },
        metadata = {
            gui_path = "/example/example_druid_component/druid_component.gui",
            fps = 60,
            settings = {
                font_size = 40,
            },
            layers = {
            },
            gizmo_steps = {
                time = 0.1,
            },
        },
    },
}