return {
    data = {
        nodes = {
        },
        metadata = {
            gizmo_steps = {
            },
            layers = {
            },
            fps = 60,
            gui_path = "/example/example_druid_component/druid_component.gui",
            settings = {
                font_size = 40,
            },
        },
        animations = {
            {
                animation_id = "default",
                duration = 2.2,
                animation_keys = {
                    {
                        duration = 0.4,
                        end_value = -42,
                        key_type = "tween",
                        property_id = "position_y",
                        node_id = "panthera",
                        easing = "outsine",
                    },
                    {
                        duration = 0.42,
                        start_value = 1,
                        key_type = "tween",
                        property_id = "scale_x",
                        easing = "outback",
                        node_id = "text",
                        end_value = 1.3,
                    },
                    {
                        duration = 0.42,
                        start_value = 1,
                        key_type = "tween",
                        property_id = "scale_y",
                        easing = "outback",
                        node_id = "text",
                        end_value = 1.3,
                    },
                    {
                        duration = 0.42,
                        start_value = 80,
                        key_type = "tween",
                        property_id = "position_y",
                        easing = "outback",
                        node_id = "text",
                        end_value = 45,
                    },
                    {
                        duration = 0.8,
                        end_value = 75,
                        key_type = "tween",
                        property_id = "position_x",
                        node_id = "panthera",
                        easing = "outsine",
                    },
                    {
                        data = "Just",
                        easing = "linear",
                        start_time = 0.22,
                        property_id = "text",
                        start_data = "Hello",
                        node_id = "text",
                        key_type = "trigger",
                    },
                    {
                        duration = 1.6,
                        start_value = -42,
                        key_type = "tween",
                        start_time = 0.4,
                        property_id = "position_y",
                        node_id = "panthera",
                        easing = "outsine",
                    },
                    {
                        duration = 0.45,
                        start_value = 1.3,
                        key_type = "tween",
                        start_time = 0.42,
                        property_id = "scale_x",
                        easing = "outsine",
                        node_id = "text",
                        end_value = 1,
                    },
                    {
                        duration = 0.45,
                        start_value = 1.3,
                        key_type = "tween",
                        start_time = 0.42,
                        property_id = "scale_y",
                        easing = "outsine",
                        node_id = "text",
                        end_value = 1,
                    },
                    {
                        duration = 0.45,
                        start_value = 45,
                        key_type = "tween",
                        start_time = 0.42,
                        property_id = "position_y",
                        easing = "outsine",
                        node_id = "text",
                        end_value = 80,
                    },
                    {
                        duration = 1.4,
                        end_value = 100,
                        key_type = "event",
                        start_time = 0.72,
                        property_id = "event",
                        event_id = "print",
                        easing = "linear",
                    },
                    {
                        duration = 0.6,
                        start_value = 75,
                        key_type = "tween",
                        start_time = 0.8,
                        property_id = "position_x",
                        easing = "outsine",
                        node_id = "panthera",
                        end_value = -65,
                    },
                    {
                        duration = 1.36,
                        key_type = "animation",
                        start_time = 0.84,
                        easing = "linear",
                        property_id = "rotate",
                        data = "rotate",
                    },
                    {
                        data = "Example",
                        easing = "linear",
                        start_time = 0.87,
                        property_id = "text",
                        start_data = "Just",
                        node_id = "text",
                        key_type = "trigger",
                    },
                    {
                        duration = 0.6,
                        start_value = -65,
                        key_type = "tween",
                        start_time = 1.4,
                        property_id = "position_x",
                        node_id = "panthera",
                        easing = "outsine",
                    },
                    {
                        end_value = 0.389,
                        key_type = "tween",
                        start_time = 2.1,
                        property_id = "color_b",
                        easing = "outsine",
                        node_id = "root",
                        start_value = 0.879,
                    },
                    {
                        end_value = 0.389,
                        key_type = "tween",
                        start_time = 2.1,
                        property_id = "color_g",
                        easing = "outsine",
                        node_id = "root",
                        start_value = 0.924,
                    },
                    {
                        end_value = 0.925,
                        key_type = "tween",
                        start_time = 2.1,
                        property_id = "color_r",
                        easing = "outsine",
                        node_id = "root",
                        start_value = 0.754,
                    },
                    {
                        duration = 0.1,
                        start_value = 0.925,
                        key_type = "tween",
                        start_time = 2.1,
                        property_id = "color_r",
                        easing = "outsine",
                        node_id = "root",
                        end_value = 0.754,
                    },
                    {
                        duration = 0.1,
                        start_value = 0.389,
                        key_type = "tween",
                        start_time = 2.1,
                        property_id = "color_b",
                        easing = "outsine",
                        node_id = "root",
                        end_value = 0.879,
                    },
                    {
                        duration = 0.1,
                        start_value = 0.389,
                        key_type = "tween",
                        start_time = 2.1,
                        property_id = "color_g",
                        easing = "outsine",
                        node_id = "root",
                        end_value = 0.924,
                    },
                },
            },
            {
                animation_id = "rotate",
                duration = 1,
                animation_keys = {
                    {
                        property_id = "rotation_z",
                        node_id = "panthera",
                        key_type = "tween",
                        easing = "outsine",
                    },
                    {
                        duration = 1,
                        end_value = -360,
                        key_type = "tween",
                        property_id = "rotation_z",
                        node_id = "panthera",
                        easing = "outsine",
                    },
                },
            },
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}