return {
    data = {
        animations = {
            {
                animation_id = "rally",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "paddle#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "paddle#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "paddle#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "position_x",
                        start_value = -320,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -220,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "position_y",
                        start_value = -220,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 300,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_x",
                        start_value = -260,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 200,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_y",
                        start_value = -160,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = -160,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = 200,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -260,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_x",
                        start_time = 0.6,
                        start_value = 300,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 200,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_y",
                        start_time = 0.6,
                        start_value = -160,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = -160,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_y",
                        start_time = 0.9,
                        start_value = 200,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "position_x",
                        start_time = 0.1,
                        start_value = -320,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "position_x",
                        start_time = 0.7,
                        start_value = 260,
                    },
                },
                duration = 1.3,
            },
            {
                animation_id = "smash",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "paddle#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "paddle#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "paddle#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "position_x",
                        start_value = -320,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -220,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "position_y",
                        start_value = -220,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -260,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_x",
                        start_value = -260,
                    },
                    {
                        duration = 0.25,
                        easing = "outcubic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_y",
                        start_value = -160,
                    },
                    {
                        duration = 0.55,
                        easing = "inback",
                        end_value = -160,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_y",
                        start_time = 0.25,
                        start_value = 260,
                    },
                    {
                        duration = 0.8,
                        easing = "outcubic",
                        end_value = 540,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.2,
                        easing = "outback",
                        end_value = 4,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "scale_x",
                        start_time = 0.15,
                        start_value = 3,
                    },
                    {
                        duration = 0.4,
                        easing = "inoutback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "scale_x",
                        start_time = 0.35,
                        start_value = 4,
                    },
                    {
                        duration = 0.2,
                        easing = "outback",
                        end_value = 4,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "scale_y",
                        start_time = 0.15,
                        start_value = 3,
                    },
                    {
                        duration = 0.4,
                        easing = "inoutback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "scale_y",
                        start_time = 0.35,
                        start_value = 4,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "serve",
                animation_keys = {
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_r",
                        start_time = 0.4,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_g",
                        start_time = 0.4,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "ball#sprite",
                        property_id = "color_b",
                        start_time = 0.4,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "paddle#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "paddle#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "paddle#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "position_x",
                        start_value = -320,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -220,
                        key_type = "tween",
                        node_id = "paddle",
                        property_id = "position_y",
                        start_value = -220,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -260,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_x",
                        start_value = -260,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -160,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "position_y",
                        start_value = -160,
                    },
                    {
                        duration = 0.3,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "scale_x",
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "scale_x",
                        start_time = 0.3,
                        start_value = 3.2,
                    },
                    {
                        duration = 0.3,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "scale_y",
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "ball",
                        property_id = "scale_y",
                        start_time = 0.3,
                        start_value = 3.2,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example2/examples/two_objects/ball.go",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
