return {
    data = {
        animations = {
            {
                animation_id = "text",
                animation_keys = {
                    {
                        data = "PANTHERA",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_title",
                        property_id = "text",
                        start_data = "PANTHERA",
                    },
                    {
                        data = "RUNTIME",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_title",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.5,
                    },
                    {
                        data = "FOR DEFOLD",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_title",
                        property_id = "text",
                        start_data = "",
                        start_time = 1,
                    },
                    {
                        data = "PANTHERA",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_title",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.5,
                    },
                    {
                        duration = 0.1,
                        easing = "outquad",
                        end_value = 0.15,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                        start_time = 0.1,
                        start_value = 0.15,
                    },
                    {
                        duration = 0.1,
                        easing = "outquad",
                        end_value = 0.15,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                        start_time = 0.5,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                        start_time = 0.6,
                        start_value = 0.15,
                    },
                    {
                        duration = 0.1,
                        easing = "outquad",
                        end_value = 0.15,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                        start_time = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                        start_time = 1.1,
                        start_value = 0.15,
                    },
                    {
                        duration = 0.1,
                        easing = "outquad",
                        end_value = 0.15,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                        start_time = 1.5,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                        start_time = 1.6,
                        start_value = 0.15,
                    },
                },
                duration = 2,
            },
            {
                animation_id = "tracking",
                animation_keys = {
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 0.4,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "text_tracking",
                        start_time = 0.6,
                        start_value = 0.4,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 1.8,
                        key_type = "tween",
                        node_id = "text_body",
                        property_id = "text_leading",
                        start_value = 1,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text_body",
                        property_id = "text_leading",
                        start_time = 0.6,
                        start_value = 1.8,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "outline",
                animation_keys = {
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "outline_r",
                        start_value = 0.129,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "outline_g",
                        start_value = 0.141,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "outline_b",
                        start_value = 0.157,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.129,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "outline_r",
                        start_time = 0.6,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.141,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "outline_g",
                        start_time = 0.6,
                        start_value = 0.502,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.157,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "outline_b",
                        start_time = 0.6,
                        start_value = 0.902,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "outline_a",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "outline_a",
                        start_time = 0.8,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "shadow_a",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "shadow_a",
                        start_time = 0.8,
                        start_value = 1,
                    },
                },
                duration = 1.3,
            },
            {
                animation_id = "color",
                animation_keys = {
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "color_r",
                        start_time = 0.6,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "color_g",
                        start_time = 0.6,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "text_title",
                        property_id = "color_b",
                        start_time = 0.6,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "text_body",
                        property_id = "color_r",
                        start_time = 0.15,
                        start_value = 0.722,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "text_body",
                        property_id = "color_g",
                        start_time = 0.15,
                        start_value = 0.741,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "text_body",
                        property_id = "color_b",
                        start_time = 0.15,
                        start_value = 0.761,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "text_body",
                        property_id = "color_r",
                        start_time = 0.75,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "text_body",
                        property_id = "color_g",
                        start_time = 0.75,
                        start_value = 0.502,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "text_body",
                        property_id = "color_b",
                        start_time = 0.75,
                        start_value = 0.902,
                    },
                },
                duration = 1.4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example2/examples/text_properties/text_properties.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
