return {
    data = {
        animations = {
            {
                animation_id = "position",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -260,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "position_x",
                        start_time = 0.5,
                        start_value = 260,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "square",
                        property_id = "position_x",
                        start_time = 1,
                        start_value = -260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = -260,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_x",
                        start_time = 0.5,
                        start_value = -260,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_x",
                        start_time = 1,
                        start_value = 260,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "scale",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 1.4,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "inback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 1.4,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "inback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 1.4,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "inback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 1.4,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "inback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 0.6,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "rotation",
                animation_keys = {
                    {
                        duration = 1.2,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1.2,
                        easing = "inoutcubic",
                        end_value = -360,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1.2,
                        easing = "inoutquad",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "rotation_z",
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "color",
                animation_keys = {
                    {
                        duration = 0.8,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.8,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_r",
                        start_time = 0.8,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.8,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_r",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.8,
                        easing = "insine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_r",
                        start_time = 0.8,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.8,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.8,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_g",
                        start_time = 0.8,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.8,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_g",
                        start_value = 0.502,
                    },
                    {
                        duration = 0.8,
                        easing = "insine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_g",
                        start_time = 0.8,
                        start_value = 0.502,
                    },
                    {
                        duration = 0.8,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.8,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_b",
                        start_time = 0.8,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.8,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_b",
                        start_value = 0.902,
                    },
                    {
                        duration = 0.8,
                        easing = "insine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_b",
                        start_time = 0.8,
                        start_value = 0.6,
                    },
                },
                duration = 1.6,
            },
            {
                animation_id = "alpha",
                animation_keys = {
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.05,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_a",
                        start_time = 0.6,
                        start_value = 0.05,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.05,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_a",
                        start_time = 0.2,
                        start_value = 1,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "color_a",
                        start_time = 0.8,
                        start_value = 0.05,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "size",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 420,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "size_x",
                        start_value = 240,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 140,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "size_y",
                        start_value = 240,
                    },
                    {
                        duration = 0.6,
                        easing = "outback",
                        end_value = 240,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "size_x",
                        start_time = 0.6,
                        start_value = 420,
                    },
                    {
                        duration = 0.6,
                        easing = "outback",
                        end_value = 240,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "size_y",
                        start_time = 0.6,
                        start_value = 140,
                    },
                },
                duration = 1.2,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/basic/basic.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
