return {
    data = {
        animations = {
            {
                animation_id = "open",
                animation_keys = {
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 165,
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "position_y",
                        start_value = 165,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "color_a",
                        start_time = 0.08,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "position_x",
                        start_time = 0.08,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_2",
                        property_id = "color_a",
                        start_time = 0.16,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "item_2",
                        property_id = "position_x",
                        start_time = 0.16,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "color_a",
                        start_time = 0.24,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "position_x",
                        start_time = 0.24,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "color_a",
                        start_time = 0.45,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "close",
                animation_keys = {
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "position_x",
                    },
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "position_x",
                    },
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "item_2",
                        property_id = "position_x",
                    },
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "position_x",
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_2",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 165,
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "position_y",
                        start_value = 165,
                    },
                    {
                        duration = 0.25,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "inback",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.4,
                        easing = "inback",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "item_2",
                        property_id = "position_x",
                        start_time = 0.07,
                    },
                    {
                        duration = 0.4,
                        easing = "inback",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "position_x",
                        start_time = 0.14,
                    },
                    {
                        duration = 0.25,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "color_a",
                        start_time = 0.15,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "inback",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "position_x",
                        start_time = 0.21,
                    },
                    {
                        duration = 0.25,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "item_2",
                        property_id = "color_a",
                        start_time = 0.22,
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "color_a",
                        start_time = 0.29,
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "color_a",
                        start_time = 0.36,
                        start_value = 1,
                    },
                },
                duration = 0.9,
            },
            {
                animation_id = "select",
                animation_keys = {
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "position_x",
                    },
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "position_x",
                    },
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "item_2",
                        property_id = "position_x",
                    },
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "position_x",
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_2",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "linear",
                        end_value = 165,
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "position_y",
                        start_value = 165,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 55,
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "position_y",
                        start_value = 165,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 26,
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "position_x",
                        start_time = 0.1,
                    },
                    {
                        duration = 0.3,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "item_1",
                        property_id = "position_x",
                        start_time = 0.25,
                        start_value = 26,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = -165,
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "position_y",
                        start_time = 0.4,
                        start_value = 55,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 26,
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "position_x",
                        start_time = 0.5,
                    },
                    {
                        duration = 0.3,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "item_3",
                        property_id = "position_x",
                        start_time = 0.65,
                        start_value = 26,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 165,
                        key_type = "tween",
                        node_id = "highlight",
                        property_id = "position_y",
                        start_time = 0.8,
                        start_value = -165,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 26,
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "position_x",
                        start_time = 0.9,
                    },
                    {
                        duration = 0.3,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "item_0",
                        property_id = "position_x",
                        start_time = 1.05,
                        start_value = 26,
                    },
                },
                duration = 1.5,
            },
            {
                animation_id = "review",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "open",
                    },
                    {
                        duration = 1.5,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "select",
                        start_time = 1,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "close",
                        start_time = 2.5,
                    },
                },
                duration = 3.4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/elastic_menu/elastic_menu.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}