return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        duration = 0.08,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                    },
                    {
                        duration = 0.48,
                        easing = "outsine",
                        end_value = 135,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_y",
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "square_animation",
                        property_id = "bounced",
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.08,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.16,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.24,
                    },
                    {
                        duration = 0.09,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.31,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.41,
                    },
                    {
                        duration = 0.41,
                        easing = "outsine",
                        end_value = -190,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_y",
                        start_time = 0.48,
                        start_value = 135,
                    },
                    {
                        duration = 0.1,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.49,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.59,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.67,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.67,
                    },
                    {
                        duration = 0.04,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.77,
                    },
                    {
                        duration = 0.06,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.8,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.86,
                    },
                    {
                        duration = 0.11,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_y",
                        start_time = 0.89,
                        start_value = -190,
                    },
                    {
                        duration = 0.06,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.94,
                    },
                    {
                        duration = 0.06,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.94,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "icon_change",
                animation_keys = {
                    {
                        easing = "outsine",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_x",
                        start_value = 0.5,
                    },
                    {
                        easing = "outsine",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_y",
                        start_value = 0.5,
                    },
                    {
                        duration = 0.2,
                        easing = "outback",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_x",
                        start_value = 0.7,
                    },
                    {
                        duration = 0.44,
                        easing = "outback",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_y",
                        start_value = 0.7,
                    },
                },
                duration = 0.44,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "example/example_template_animations/example_template_animations.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
                square_animation = require("example.example_template_animations.templates.square_animation_panthera"),
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}