return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        data = "example/avatar_bandit",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/ui_circle",
                    },
                    {
                        duration = 0.078,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                    },
                    {
                        duration = 0.48,
                        easing = "outsine",
                        end_value = 135,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_y",
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "square_animation",
                        property_id = "bounced",
                    },
                    {
                        duration = 0.078,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.078,
                    },
                    {
                        data = "example/avatar_dragon",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_bandit",
                        start_time = 0.079,
                    },
                    {
                        duration = 0.078,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.157,
                    },
                    {
                        data = "example/avatar_dumb",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_dragon",
                        start_time = 0.159,
                    },
                    {
                        data = "example/avatar_girl",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_dumb",
                        start_time = 0.233,
                    },
                    {
                        duration = 0.078,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.235,
                    },
                    {
                        duration = 0.088,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.313,
                    },
                    {
                        data = "example/avatar_king",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_girl",
                        start_time = 0.314,
                    },
                    {
                        data = "example/avatar_monkey",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_king",
                        start_time = 0.411,
                    },
                    {
                        duration = 0.078,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.412,
                    },
                    {
                        duration = 0.41,
                        easing = "outsine",
                        end_value = -190,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_y",
                        start_time = 0.48,
                        start_value = 135,
                    },
                    {
                        duration = 0.098,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.49,
                    },
                    {
                        data = "example/avatar_octopus",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_monkey",
                        start_time = 0.491,
                    },
                    {
                        duration = 0.078,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.588,
                    },
                    {
                        data = "example/avatar_pirate",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_octopus",
                        start_time = 0.589,
                    },
                    {
                        duration = 0.078,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.666,
                    },
                    {
                        duration = 0.078,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.666,
                    },
                    {
                        data = "example/avatar_queen",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_pirate",
                        start_time = 0.668,
                    },
                    {
                        duration = 0.038,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.765,
                    },
                    {
                        data = "example/avatar_unipig",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_queen",
                        start_time = 0.767,
                    },
                    {
                        duration = 0.058,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.803,
                    },
                    {
                        duration = 0.078,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.862,
                    },
                    {
                        data = "example/avatar_voodoo",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_unipig",
                        start_time = 0.864,
                    },
                    {
                        duration = 0.11,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_y",
                        start_time = 0.89,
                        start_value = -190,
                    },
                    {
                        data = "example/avatar_wizard",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_voodoo",
                        start_time = 0.94,
                    },
                    {
                        duration = 0.06,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.94,
                    },
                    {
                        duration = 0.06,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "icon_change",
                        start_time = 0.94,
                    },
                    {
                        data = "example/ui_circle",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "circle",
                        property_id = "texture",
                        start_data = "example/avatar_wizard",
                        start_time = 1,
                    },
                },
                duration = 1,
                formatted_duration = "1.0",
            },
            {
                animation_id = "icon_change",
                animation_keys = {
                    {
                        easing = "outsine",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_x",
                        start_value = 0.5,
                    },
                    {
                        easing = "outsine",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_y",
                        start_value = 0.5,
                    },
                    {
                        duration = 0.2,
                        easing = "outback",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_x",
                        start_value = 0.7,
                    },
                    {
                        duration = 0.44,
                        easing = "outback",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_y",
                        start_value = 0.7,
                    },
                },
                duration = 0.44,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "example/example_template_animations/example_template_animations.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
                square_animation = require("example.example_template_animations.templates.square_animation_panthera"),
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}