#!/bin/bash
# https://github.com/Insality/defold-deployer

# You can point bob version for project in format "[filename]:sha"
bob_sha=":1aafd0a262ff40214ed7f51302d92fa587c607ef"

# Select Defold channel. Values: stable, beta, alpha
bob_channel="stable"

# If true, it will check and download latest bob version. It will ignore bob_sha param
use_latest_bob=false

# Select Defold build server
build_server="https://build.defold.com"

# Pre-build hook bash script path. The path relative from game project folder
pre_build_script=false

# Post-build hook bash script path. The path relative from game project folder
post_build_script=false

# Set patch (last value after dot) game version value as total git commits count (1.2.0 -> 1.2.{commits_count})
# You allow to get SHA commit from version via: git rev-list --all --reverse | sed -n {N}p
enable_incremental_version=true

# Use git commits count as android.version_code on build
enable_incremental_android_version_code=true

# Local resource cache folder for deployer script. This folder will be added to .gitignore if exists
resource_cache_local=".cache_deployer"

# Exclude folders from build
# exclude_folders=""

# Use settings file for Android platform
# settings_android=./settings/android.ini

# Use settings file for iOS platform
# settings_ios=./settings/ios.ini

# Path to android keystore for debug
# android_keystore_dev="./provisions/defold.keystore"

# Path to android keystore for release
# android_keystore_dist="./provisions/defold.keystore"

# Path to android keystore password for debug. This file should contains keystore password
# android_keystore_password_dev="./provisions/password.txt"

# Path to android keystore password for release. This file should contains keystore password
# android_keystore_password_dist="./provisions/password.txt"

# Name of alias from provided keystore to use for android development build
# android_keystore_alias_dev=""

# Name of alias from provided keystore to use for android release build
# android_keystore_alias_dist=""

# ID of your ios development identity
# ios_identity_dev="DDCCBBAA"

# ID of your iod distribution identity
# ios_identity_dist="AABBCCDD"

# Path to ios development mobileprovision
# ios_prov_dev="./provisions/ios_development.mobileprovision"

# Path to ios distribution mobileprovision
# ios_prov_dist="./provisions/ios_distribution.mobileprovision"

# If true, add `-l yes` build param for publish live content
is_live_content=false

# Set to true, if you do not need to strip executables
no_strip_executable=false

# Is need to build html report
is_build_html_report=true

