return {
    data = {
        animations = {
            {
                animation_id = "triggers",
                animation_keys = {
                    {
                        data = "Loading...",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_state",
                        property_id = "text",
                        start_data = "Ready",
                    },
                    {
                        data = "Almost there",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_state",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.9,
                    },
                    {
                        data = "Done!",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_state",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.5,
                    },
                    {
                        data = "false",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "icon_done",
                        property_id = "visible",
                        start_data = "false",
                    },
                    {
                        data = "true",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "icon_done",
                        property_id = "visible",
                        start_data = "",
                        start_time = 1.5,
                    },
                    {
                        duration = 1.5,
                        easing = "inoutsine",
                        end_value = 300,
                        key_type = "tween",
                        node_id = "runner",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.5,
                        easing = "inoutsine",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "runner",
                        property_id = "rotation_z",
                    },
                },
                duration = 2,
            },
            {
                animation_id = "events",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        event_id = "start",
                        key_type = "event",
                        property_id = "event",
                    },
                    {
                        duration = 1.5,
                        easing = "inoutsine",
                        end_value = 100,
                        event_id = "progress",
                        key_type = "event",
                        property_id = "event",
                    },
                    {
                        data = "half way",
                        duration = 0,
                        easing = "linear",
                        event_id = "checkpoint",
                        key_type = "event",
                        node_id = "runner",
                        property_id = "event",
                        start_time = 0.75,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        event_id = "finish",
                        key_type = "event",
                        property_id = "event",
                        start_time = 1.5,
                    },
                    {
                        duration = 1.5,
                        easing = "inoutsine",
                        end_value = 300,
                        key_type = "tween",
                        node_id = "runner",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 0.4,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_a",
                        start_time = 1.5,
                        start_value = 0.4,
                    },
                },
                duration = 2,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/events/events.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
