return {
    data = {
        animations = {
            {
                animation_id = "type",
                animation_keys = {
                    {
                        data = "",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                    },
                    {
                        data = "P",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.045,
                    },
                    {
                        data = "Pa",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.09,
                    },
                    {
                        data = "Pan",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.135,
                    },
                    {
                        data = "Pant",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.18,
                    },
                    {
                        data = "Panth",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.225,
                    },
                    {
                        data = "Panthe",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.27,
                    },
                    {
                        data = "Panther",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.315,
                    },
                    {
                        data = "Panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.36,
                    },
                    {
                        data = "Panthera ",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.405,
                    },
                    {
                        data = "Panthera a",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.45,
                    },
                    {
                        data = "Panthera an",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.495,
                    },
                    {
                        data = "Panthera ani",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.54,
                    },
                    {
                        data = "Panthera anim",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.585,
                    },
                    {
                        data = "Panthera anima",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.63,
                    },
                    {
                        data = "Panthera animat",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.675,
                    },
                    {
                        data = "Panthera animate",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.72,
                    },
                    {
                        data = "Panthera animates",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.765,
                    },
                    {
                        data = "Panthera animates ",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.81,
                    },
                    {
                        data = "Panthera animates y",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.855,
                    },
                    {
                        data = "Panthera animates yo",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.9,
                    },
                    {
                        data = "Panthera animates you",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.945,
                    },
                    {
                        data = "Panthera animates your",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.99,
                    },
                    {
                        data = "Panthera animates your ",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.035,
                    },
                    {
                        data = "Panthera animates your i",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.08,
                    },
                    {
                        data = "Panthera animates your in",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.125,
                    },
                    {
                        data = "Panthera animates your int",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.17,
                    },
                    {
                        data = "Panthera animates your inte",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.215,
                    },
                    {
                        data = "Panthera animates your inter",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.26,
                    },
                    {
                        data = "Panthera animates your interf",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.305,
                    },
                    {
                        data = "Panthera animates your interfa",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.35,
                    },
                    {
                        data = "Panthera animates your interfac",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.395,
                    },
                    {
                        data = "Panthera animates your interface",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.44,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "cursor",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -6,
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "rotation_z",
                        start_time = 0.2,
                        start_value = -6,
                    },
                },
                duration = 1.69,
            },
            {
                animation_id = "blink",
                animation_keys = {
                    {
                        data = "Panthera animates your interface",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                    },
                    {
                        duration = 0.18,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "cursor",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.18,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "cursor",
                        property_id = "color_a",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.18,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "cursor",
                        property_id = "color_a",
                        start_time = 0.4,
                        start_value = 1,
                    },
                    {
                        duration = 0.18,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "cursor",
                        property_id = "color_a",
                        start_time = 0.6000000000000001,
                    },
                    {
                        duration = 0.18,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "cursor",
                        property_id = "color_a",
                        start_time = 0.8,
                        start_value = 1,
                    },
                    {
                        duration = 0.18,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "cursor",
                        property_id = "color_a",
                        start_time = 1,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "shake",
                animation_keys = {
                    {
                        data = "Panthera animates your interface",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "cursor",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.07,
                        easing = "outsine",
                        end_value = 18,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.07,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "position_x",
                        start_time = 0.07,
                        start_value = -14,
                    },
                    {
                        duration = 0.07,
                        easing = "outsine",
                        end_value = 10,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "position_x",
                        start_time = 0.14,
                        start_value = 10,
                    },
                    {
                        duration = 0.07,
                        easing = "outsine",
                        end_value = -6,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "position_x",
                        start_time = 0.21000000000000002,
                        start_value = -6,
                    },
                    {
                        duration = 0.07,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "position_x",
                        start_time = 0.28,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.1,
                        easing = "outsine",
                        end_value = 0.35,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_r",
                        start_value = 0.173,
                    },
                    {
                        duration = 0.1,
                        easing = "outsine",
                        end_value = 0.2,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_g",
                        start_value = 0.184,
                    },
                    {
                        duration = 0.1,
                        easing = "outsine",
                        end_value = 0.22,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_b",
                        start_value = 0.204,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_r",
                        start_time = 0.35,
                        start_value = 0.35,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_g",
                        start_time = 0.35,
                        start_value = 0.2,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "color_b",
                        start_time = 0.35,
                        start_value = 0.22,
                    },
                },
                duration = 0.8,
            },
            {
                animation_id = "dialogue",
                animation_keys = {
                    {
                        duration = 1.69,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "type",
                    },
                    {
                        duration = 1.2,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "blink",
                        start_time = 1.69,
                    },
                    {
                        data = "",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_line",
                        property_id = "text",
                        start_data = "",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "cursor",
                        property_id = "color_a",
                        start_value = 1,
                    },
                },
                duration = 2.89,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/typewriter/typewriter.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
