return {
    data = {
        animations = {
            {
                animation_id = "orbit",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "pivot#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "pivot#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "pivot#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.6,
                        easing = "inoutsine",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "pivot",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "dot1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "dot1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "dot1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.6,
                        easing = "inoutsine",
                        end_value = -360,
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "dot2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "dot2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "dot2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.6,
                        easing = "inoutsine",
                        end_value = -360,
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "dot3#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "dot3#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "dot3#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.6,
                        easing = "inoutsine",
                        end_value = -360,
                        key_type = "tween",
                        node_id = "dot3",
                        property_id = "rotation_z",
                    },
                },
                duration = 1.6,
            },
            {
                animation_id = "pulse",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "pivot#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "pivot#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "pivot#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "pivot",
                        property_id = "scale_x",
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "pivot",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 3,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "pivot",
                        property_id = "scale_y",
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "pivot",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 3,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "dot1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "dot1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "dot1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "dot2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "dot2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "dot2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "dot3#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "dot3#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "dot3#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "wave",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "pivot#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "pivot#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "pivot#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "dot1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "dot1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "dot1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.45,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_y",
                        start_time = 0.35,
                        start_value = 120,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "dot2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "dot2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "dot2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_y",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.45,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 120,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "dot3#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "dot3#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "dot3#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "dot3",
                        property_id = "position_y",
                        start_time = 0.3,
                    },
                    {
                        duration = 0.45,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "dot3",
                        property_id = "position_y",
                        start_time = 0.6499999999999999,
                        start_value = 120,
                    },
                },
                duration = 1.2,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example2/examples/hierarchy/hierarchy.collection",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
