return {
    data = {
        animations = {
            {
                animation_id = "spin",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_r",
                        start_value = 0.173,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_g",
                        start_value = 0.184,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_b",
                        start_value = 0.204,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "outcubic",
                        end_value = -1155,
                        key_type = "tween",
                        node_id = "reel_l_strip",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.12,
                        easing = "outsine",
                        end_value = -1129,
                        key_type = "tween",
                        node_id = "reel_l_strip",
                        property_id = "position_y",
                        start_time = 1,
                        start_value = -1155,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = -1155,
                        key_type = "tween",
                        node_id = "reel_l_strip",
                        property_id = "position_y",
                        start_time = 1.12,
                        start_value = -1129,
                    },
                    {
                        duration = 1.4,
                        easing = "outcubic",
                        end_value = -2640,
                        key_type = "tween",
                        node_id = "reel_c_strip",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.12,
                        easing = "outsine",
                        end_value = -2614,
                        key_type = "tween",
                        node_id = "reel_c_strip",
                        property_id = "position_y",
                        start_time = 1.4,
                        start_value = -2640,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = -2640,
                        key_type = "tween",
                        node_id = "reel_c_strip",
                        property_id = "position_y",
                        start_time = 1.52,
                        start_value = -2614,
                    },
                    {
                        duration = 1.8,
                        easing = "outcubic",
                        end_value = -2145,
                        key_type = "tween",
                        node_id = "reel_r_strip",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.12,
                        easing = "outsine",
                        end_value = -2119,
                        key_type = "tween",
                        node_id = "reel_r_strip",
                        property_id = "position_y",
                        start_time = 1.8,
                        start_value = -2145,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = -2145,
                        key_type = "tween",
                        node_id = "reel_r_strip",
                        property_id = "position_y",
                        start_time = 1.92,
                        start_value = -2119,
                    },
                },
                duration = 2.4,
            },
            {
                animation_id = "nudge",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_r",
                        start_value = 0.173,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_g",
                        start_value = 0.184,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_b",
                        start_value = 0.204,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.22,
                        easing = "outcubic",
                        end_value = -185,
                        key_type = "tween",
                        node_id = "reel_l_strip",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = -165,
                        key_type = "tween",
                        node_id = "reel_l_strip",
                        property_id = "position_y",
                        start_time = 0.22,
                        start_value = -185,
                    },
                    {
                        duration = 0.22,
                        easing = "outcubic",
                        end_value = -185,
                        key_type = "tween",
                        node_id = "reel_c_strip",
                        property_id = "position_y",
                        start_time = 0.07,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = -165,
                        key_type = "tween",
                        node_id = "reel_c_strip",
                        property_id = "position_y",
                        start_time = 0.29000000000000004,
                        start_value = -185,
                    },
                    {
                        duration = 0.22,
                        easing = "outcubic",
                        end_value = -185,
                        key_type = "tween",
                        node_id = "reel_r_strip",
                        property_id = "position_y",
                        start_time = 0.14,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = -165,
                        key_type = "tween",
                        node_id = "reel_r_strip",
                        property_id = "position_y",
                        start_time = 0.36,
                        start_value = -185,
                    },
                },
                duration = 0.9,
            },
            {
                animation_id = "win",
                animation_keys = {
                    {
                        duration = 0.12,
                        easing = "outsine",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_r",
                        start_value = 0.173,
                    },
                    {
                        duration = 0.12,
                        easing = "outsine",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_g",
                        start_value = 0.184,
                    },
                    {
                        duration = 0.12,
                        easing = "outsine",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_b",
                        start_value = 0.204,
                    },
                    {
                        duration = 0.18,
                        easing = "outsine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_r",
                        start_time = 0.12,
                        start_value = 0.173,
                    },
                    {
                        duration = 0.18,
                        easing = "outsine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_g",
                        start_time = 0.12,
                        start_value = 0.184,
                    },
                    {
                        duration = 0.18,
                        easing = "outsine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_b",
                        start_time = 0.12,
                        start_value = 0.204,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_r",
                        start_time = 0.6,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_g",
                        start_time = 0.6,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_b",
                        start_time = 0.6,
                        start_value = 0.333,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_a",
                        start_value = 0.35,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        end_value = 0.35,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_a",
                        start_time = 0.6,
                        start_value = 1,
                    },
                    {
                        duration = 0.22,
                        easing = "outback",
                        end_value = 1.16,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_x",
                        start_time = 0.22,
                        start_value = 1.16,
                    },
                    {
                        duration = 0.22,
                        easing = "outback",
                        end_value = 1.16,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_y",
                        start_time = 0.22,
                        start_value = 1.16,
                    },
                    {
                        duration = 0.22,
                        easing = "outback",
                        end_value = 1.16,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_x",
                        start_time = 0.09,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_x",
                        start_time = 0.31,
                        start_value = 1.16,
                    },
                    {
                        duration = 0.22,
                        easing = "outback",
                        end_value = 1.16,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_y",
                        start_time = 0.09,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_y",
                        start_time = 0.31,
                        start_value = 1.16,
                    },
                    {
                        duration = 0.22,
                        easing = "outback",
                        end_value = 1.16,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_x",
                        start_time = 0.18,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_x",
                        start_time = 0.4,
                        start_value = 1.16,
                    },
                    {
                        duration = 0.22,
                        easing = "outback",
                        end_value = 1.16,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_y",
                        start_time = 0.18,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_y",
                        start_time = 0.4,
                        start_value = 1.16,
                    },
                },
                duration = 1.3,
            },
            {
                animation_id = "review",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_r",
                        start_value = 0.173,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_g",
                        start_value = 0.184,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "frame",
                        property_id = "color_b",
                        start_value = 0.204,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "payline",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_l",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_c",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "reel_r",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "nudge",
                    },
                    {
                        duration = 2.4,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "spin",
                        start_time = 0.9,
                    },
                    {
                        duration = 1.3,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "win",
                        start_time = 3.3,
                    },
                },
                duration = 4.6,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/slot_machine/slot_machine.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
