return {
    data = {
        animations = {
            {
                animation_id = "flip_both",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots_top",
                        property_id = "flip",
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots_bottom",
                        property_id = "flip",
                        start_time = 0.2,
                    },
                    {
                        duration = 1.2,
                        easing = "inoutsine",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "rotation_z",
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "bounce_wave",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots_top",
                        property_id = "bounce",
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots_bottom",
                        property_id = "bounce",
                        start_time = 0.5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 1.2,
                    },
                },
                duration = 1.5,
            },
            {
                animation_id = "what_together",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots_top",
                        property_id = "what",
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots_bottom",
                        property_id = "what",
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1.4,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_time = 0.2,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1.4,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_time = 0.2,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_time = 0.7,
                        start_value = 1.4,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_time = 0.7,
                        start_value = 1.4,
                    },
                },
                duration = 1.2,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example2/examples/nested/nested.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
                dots_top = require("example2.examples.dots.dots_panthera"),
                dots_bottom = require("example2.examples.dots.dots_panthera"),
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
