return {
    data = {
        animations = {
            {
                animation_id = "fill",
                animation_keys = {
                    {
                        duration = 0.25,
                        easing = "incubic",
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "fill_angle",
                        start_value = 360,
                    },
                    {
                        duration = 0.75,
                        easing = "outcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "fill_angle",
                        start_time = 0.25,
                    },
                    {
                        duration = 1,
                        easing = "inoutcubic",
                        end_value = 90,
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "rotation_z",
                    },
                },
                duration = 1,
            },
            {
                animation_id = "donut",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 100,
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "inner_radius",
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "inner_radius",
                        start_time = 0.5,
                        start_value = 100,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "spinner",
                animation_keys = {
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 90,
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "inner_radius",
                    },
                    {
                        duration = 0.45,
                        easing = "inoutsine",
                        end_value = 60,
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "fill_angle",
                        start_value = 360,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutsine",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "fill_angle",
                        start_time = 0.45,
                        start_value = 60,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        end_value = -360,
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "pie",
                        property_id = "inner_radius",
                        start_time = 0.9,
                        start_value = 90,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "slice9",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 4,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "slice9_left",
                        start_value = 32,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 4,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "slice9_right",
                        start_value = 32,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 4,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "slice9_top",
                        start_value = 32,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 4,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "slice9_bottom",
                        start_value = 32,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 32,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "slice9_left",
                        start_time = 0.6,
                        start_value = 4,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 32,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "slice9_right",
                        start_time = 0.6,
                        start_value = 4,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 32,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "slice9_top",
                        start_time = 0.6,
                        start_value = 4,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 32,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "slice9_bottom",
                        start_time = 0.6,
                        start_value = 4,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "size_x",
                        start_value = 300,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 300,
                        key_type = "tween",
                        node_id = "panel",
                        property_id = "size_x",
                        start_time = 0.6,
                        start_value = 120,
                    },
                },
                duration = 1.1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/pie_slice9/pie_slice9.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
