return {
    data = {
        animations = {
            {
                animation_id = "orbit",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "moon#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "moon#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "moon#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.6,
                        easing = "linear",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "planet",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1.6,
                        easing = "linear",
                        end_value = -360,
                        key_type = "tween",
                        node_id = "moon",
                        property_id = "rotation_z",
                    },
                },
                duration = 1.6,
            },
            {
                animation_id = "pulse",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "moon#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "moon#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "moon#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "planet",
                        property_id = "scale_x",
                        start_value = 2.4,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 2.4,
                        key_type = "tween",
                        node_id = "planet",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 3,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.3,
                        key_type = "tween",
                        node_id = "moon",
                        property_id = "scale_x",
                        start_time = 0.25,
                        start_value = 0.5,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "moon",
                        property_id = "scale_x",
                        start_time = 0.65,
                        start_value = 0.3,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "planet",
                        property_id = "scale_y",
                        start_value = 2.4,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 2.4,
                        key_type = "tween",
                        node_id = "planet",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 3,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.3,
                        key_type = "tween",
                        node_id = "moon",
                        property_id = "scale_y",
                        start_time = 0.25,
                        start_value = 0.5,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "moon",
                        property_id = "scale_y",
                        start_time = 0.65,
                        start_value = 0.3,
                    },
                },
                duration = 1.1,
            },
            {
                animation_id = "eclipse",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_r",
                        start_time = 0.5,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_g",
                        start_time = 0.5,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_b",
                        start_time = 0.5,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_r",
                        start_time = 1,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_g",
                        start_time = 1,
                        start_value = 0.502,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "planet#sprite",
                        property_id = "color_b",
                        start_time = 1,
                        start_value = 0.902,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "moon#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "moon#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "moon#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.5,
                        easing = "inoutsine",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "planet",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.75,
                        easing = "inoutsine",
                        end_value = 60,
                        key_type = "tween",
                        node_id = "moon",
                        property_id = "position_x",
                        start_value = 120,
                    },
                    {
                        duration = 0.75,
                        easing = "inoutsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "moon",
                        property_id = "position_x",
                        start_time = 0.75,
                        start_value = 60,
                    },
                },
                duration = 1.5,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/orbit/orbit.collection",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
