---@diagnostic disable: missing-parameter, param-type-mismatch
local panthera_editor = require("panthera.editor_scripts.panthera_editor")

local M = {}


---@param str string
---@param ending string
---@return boolean
local function ends_with(str, ending)
	return ending == "" or str:sub(-#ending) == ending
end


---@param path string
---@param file_data string
---@return boolean
local function is_panthera_animation_file(path, file_data)
	local is_json = ends_with(path, ".json")
	local is_lua = ends_with(path, ".lua")

	if is_json then
		-- Check contains "type":"animation_editor"
		return (not not file_data:find("\"type\"%s*:%s*\"animation_editor\""))
	end

	if is_lua then
		-- Check contains type = "animation_editor"
		return (not not file_data:find("type%s*=%s*\"animation_editor\""))
	end

	return false
end


function M.get_commands()
	return {
		{
			label = "[Panthera] Edit Panthera Animation",
			locations = { "Assets" , "Edit" },
			query = { selection = { type = "resource", cardinality = "one" } },
			active = function(opts)
				if not editor.can_get(opts.selection, "text") then
					return false
				end

				local path = editor.get(opts.selection, "path")
				local text = editor.get(opts.selection, "text")
				local is_extension_ok = ends_with(path, ".lua") or ends_with(path, ".json")
				if not is_extension_ok then
					return false
				end

				return is_panthera_animation_file(path, text)
			end,
			run = function(opts)
				local project_path = editor.external_file_attributes(".").path
				panthera_editor.run("open", project_path .. editor.get(opts.selection, "path"))
			end
		},

		{
			label = "[Panthera] Create Panthera Animation",
			locations = { "Assets" , "Edit" },
			query = { selection = { type = "resource", cardinality = "one" } },
			active = function(opts)
				local path = editor.get(opts.selection, "path")
				return ends_with(path, ".collection") or ends_with(path, ".gui") or ends_with(path, ".go")
			end,
			run = function(opts)
				local project_path = editor.external_file_attributes(".").path
				panthera_editor.run("create", project_path .. editor.get(opts.selection, "path"))
			end
		},

		{
			label = "[Panthera] Open Panthera Editor",
			locations = { "Project" },
			run = function()
				panthera_editor.run(nil, nil)
			end
		},

		{
			label = "[Panthera] Update Panthera Editor",
			locations = { "Project" },
			run = function()
				panthera_editor.update()
			end
		},
	}
end


function M.get_prefs_schema()
	return panthera_editor.get_prefs_schema()
end


return M
