return {
    data = {
        animations = {
            {
                animation_id = "pulse",
                animation_keys = {
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "inoutback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_x",
                        start_time = 0.25,
                        start_value = 1.25,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "inoutback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_y",
                        start_time = 0.25,
                        start_value = 1.25,
                    },
                },
                duration = 0.6,
            },
            {
                animation_id = "pulse_and_flip",
                animation_keys = {
                    {
                        duration = 0.6,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "pulse",
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots",
                        property_id = "flip",
                        start_time = 0.1,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "rotation_z",
                        start_time = 0.6,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "finale",
                animation_keys = {
                    {
                        duration = 0.6,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "pulse",
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots",
                        property_id = "bounce",
                    },
                    {
                        duration = 0.6,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "pulse",
                        start_time = 0.8,
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots",
                        property_id = "what",
                        start_time = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_time = 1,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_time = 1,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.6,
                        easing = "outback",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_time = 1.4,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.6,
                        easing = "outback",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_time = 1.4,
                        start_value = 1.1,
                    },
                },
                duration = 2,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example2/examples/combined/combined.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
                dots = require("example2.examples.dots.dots_panthera"),
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
