return {
    data = {
        animations = {
            {
                animation_id = "wobble",
                animation_keys = {
                    {
                        data = "72%",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_percent",
                        property_id = "text",
                        start_data = "72%",
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 294,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 226,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "size_y",
                        start_time = 0.3,
                        start_value = 294,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "size_y",
                        start_time = 0.6,
                        start_value = 226,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 294,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "size_y",
                        start_time = 0.11,
                        start_value = 260,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 226,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "size_y",
                        start_time = 0.41,
                        start_value = 294,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "size_y",
                        start_time = 0.71,
                        start_value = 226,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 294,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "size_y",
                        start_time = 0.22,
                        start_value = 260,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 226,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "size_y",
                        start_time = 0.52,
                        start_value = 294,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "size_y",
                        start_time = 0.82,
                        start_value = 226,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 294,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "size_y",
                        start_time = 0.33,
                        start_value = 260,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 226,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "size_y",
                        start_time = 0.63,
                        start_value = 294,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "size_y",
                        start_time = 0.9299999999999999,
                        start_value = 226,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 294,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "size_y",
                        start_time = 0.44,
                        start_value = 260,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 226,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "size_y",
                        start_time = 0.74,
                        start_value = 294,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "size_y",
                        start_time = 1.04,
                        start_value = 226,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 294,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "size_y",
                        start_time = 0.55,
                        start_value = 260,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 226,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "size_y",
                        start_time = 0.8500000000000001,
                        start_value = 294,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "size_y",
                        start_time = 1.15,
                        start_value = 226,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 294,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "size_y",
                        start_time = 0.66,
                        start_value = 260,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 226,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "size_y",
                        start_time = 0.96,
                        start_value = 294,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "size_y",
                        start_time = 1.26,
                        start_value = 226,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 294,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "size_y",
                        start_time = 0.77,
                        start_value = 260,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 226,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "size_y",
                        start_time = 1.07,
                        start_value = 294,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "size_y",
                        start_time = 1.37,
                        start_value = 226,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 294,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "size_y",
                        start_time = 0.88,
                        start_value = 260,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 226,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "size_y",
                        start_time = 1.18,
                        start_value = 294,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "size_y",
                        start_time = 1.48,
                        start_value = 226,
                    },
                },
                duration = 1.6,
            },
            {
                animation_id = "drain",
                animation_keys = {
                    {
                        data = "72%",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_percent",
                        property_id = "text",
                        start_data = "72%",
                    },
                    {
                        data = "48%",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_percent",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.25,
                    },
                    {
                        data = "23%",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_percent",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.5,
                    },
                    {
                        data = "8%",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_percent",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.8,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "size_y",
                        start_time = 0.4,
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "color_r",
                        start_time = 0.4,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "color_g",
                        start_time = 0.4,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "color_b",
                        start_time = 0.4,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "size_y",
                        start_time = 0.35000000000000003,
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "color_r",
                        start_time = 0.35000000000000003,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "color_g",
                        start_time = 0.35000000000000003,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "color_b",
                        start_time = 0.35000000000000003,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "size_y",
                        start_time = 0.30000000000000004,
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "color_r",
                        start_time = 0.30000000000000004,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "color_g",
                        start_time = 0.30000000000000004,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "color_b",
                        start_time = 0.30000000000000004,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "size_y",
                        start_time = 0.25,
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "color_r",
                        start_time = 0.25,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "color_g",
                        start_time = 0.25,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "color_b",
                        start_time = 0.25,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "size_y",
                        start_time = 0.2,
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "color_r",
                        start_time = 0.2,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "color_g",
                        start_time = 0.2,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "color_b",
                        start_time = 0.2,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "size_y",
                        start_time = 0.15000000000000002,
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "color_r",
                        start_time = 0.15000000000000002,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "color_g",
                        start_time = 0.15000000000000002,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "color_b",
                        start_time = 0.15000000000000002,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "size_y",
                        start_time = 0.1,
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "color_r",
                        start_time = 0.1,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "color_g",
                        start_time = 0.1,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "color_b",
                        start_time = 0.1,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "size_y",
                        start_time = 0.05,
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "color_r",
                        start_time = 0.05,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "color_g",
                        start_time = 0.05,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "color_b",
                        start_time = 0.05,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "fill",
                animation_keys = {
                    {
                        data = "8%",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_percent",
                        property_id = "text",
                        start_data = "72%",
                    },
                    {
                        data = "41%",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_percent",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.35,
                    },
                    {
                        data = "67%",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_percent",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.6,
                    },
                    {
                        data = "72%",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_percent",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.85,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 286,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "size_y",
                        start_value = 30,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "size_y",
                        start_time = 0.55,
                        start_value = 286,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "color_r",
                        start_time = 0.4,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "color_g",
                        start_time = 0.4,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "slice_0",
                        property_id = "color_b",
                        start_time = 0.4,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 286,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "size_y",
                        start_time = 0.05,
                        start_value = 30,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "size_y",
                        start_time = 0.6000000000000001,
                        start_value = 286,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "color_r",
                        start_time = 0.45,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "color_g",
                        start_time = 0.45,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "slice_1",
                        property_id = "color_b",
                        start_time = 0.45,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 286,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "size_y",
                        start_time = 0.1,
                        start_value = 30,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "size_y",
                        start_time = 0.65,
                        start_value = 286,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "color_r",
                        start_time = 0.5,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "color_g",
                        start_time = 0.5,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "slice_2",
                        property_id = "color_b",
                        start_time = 0.5,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 286,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "size_y",
                        start_time = 0.15000000000000002,
                        start_value = 30,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "size_y",
                        start_time = 0.7000000000000001,
                        start_value = 286,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "color_r",
                        start_time = 0.55,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "color_g",
                        start_time = 0.55,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "slice_3",
                        property_id = "color_b",
                        start_time = 0.55,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 286,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "size_y",
                        start_time = 0.2,
                        start_value = 30,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "size_y",
                        start_time = 0.75,
                        start_value = 286,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "color_r",
                        start_time = 0.6000000000000001,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "color_g",
                        start_time = 0.6000000000000001,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "slice_4",
                        property_id = "color_b",
                        start_time = 0.6000000000000001,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 286,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "size_y",
                        start_time = 0.25,
                        start_value = 30,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "size_y",
                        start_time = 0.8,
                        start_value = 286,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "color_r",
                        start_time = 0.65,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "color_g",
                        start_time = 0.65,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "slice_5",
                        property_id = "color_b",
                        start_time = 0.65,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 286,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "size_y",
                        start_time = 0.30000000000000004,
                        start_value = 30,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "size_y",
                        start_time = 0.8500000000000001,
                        start_value = 286,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "color_r",
                        start_time = 0.7000000000000001,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "color_g",
                        start_time = 0.7000000000000001,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "slice_6",
                        property_id = "color_b",
                        start_time = 0.7000000000000001,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 286,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "size_y",
                        start_time = 0.35000000000000003,
                        start_value = 30,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "size_y",
                        start_time = 0.9000000000000001,
                        start_value = 286,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "color_r",
                        start_time = 0.75,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "color_g",
                        start_time = 0.75,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "slice_7",
                        property_id = "color_b",
                        start_time = 0.75,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "size_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 286,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "size_y",
                        start_time = 0.4,
                        start_value = 30,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "size_y",
                        start_time = 0.9500000000000001,
                        start_value = 286,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "color_r",
                        start_time = 0.8,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "color_g",
                        start_time = 0.8,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "slice_8",
                        property_id = "color_b",
                        start_time = 0.8,
                        start_value = 0.6,
                    },
                },
                duration = 1.4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/liquid_bar/liquid_bar.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
