return {
    data = {
        animations = {
            {
                animation_id = "move",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_x",
                        start_value = -260,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 140,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_y",
                        start_value = -140,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -260,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_x",
                        start_time = 0.6,
                        start_value = 260,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -140,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "position_y",
                        start_time = 0.6,
                        start_value = 140,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "square",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -120,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "position_y",
                        start_value = 120,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "square",
                        property_id = "position_x",
                        start_time = 0.6,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "position_y",
                        start_time = 0.6,
                        start_value = -120,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -260,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_x",
                        start_value = 260,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 140,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_y",
                        start_value = -140,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_x",
                        start_time = 0.6,
                        start_value = -260,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -140,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_y",
                        start_time = 0.6,
                        start_value = 140,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "spin",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.2,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.2,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "rotation_z",
                        start_time = 0.15,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.2,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "rotation_z",
                        start_time = 0.3,
                    },
                },
                duration = 1.5,
            },
            {
                animation_id = "pulse",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 2.8,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_x",
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_x",
                        start_time = 0.4,
                        start_value = 2.8,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 2.8,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_y",
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "circle",
                        property_id = "scale_y",
                        start_time = 0.4,
                        start_value = 2.8,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 5.6,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_x",
                        start_time = 0.1,
                        start_value = 4,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 4,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 5.6,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 5.6,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_y",
                        start_time = 0.1,
                        start_value = 4,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 4,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 5.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1.9599999999999997,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_x",
                        start_time = 0.2,
                        start_value = 1.4,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 1.4,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_x",
                        start_time = 0.6000000000000001,
                        start_value = 1.9599999999999997,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1.9599999999999997,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_y",
                        start_time = 0.2,
                        start_value = 1.4,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 1.4,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_y",
                        start_time = 0.6000000000000001,
                        start_value = 1.9599999999999997,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "tint",
                animation_keys = {
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_r",
                        start_time = 0.6,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_g",
                        start_time = 0.6,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "circle#sprite",
                        property_id = "color_b",
                        start_time = 0.6,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_r",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_g",
                        start_value = 0.502,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_b",
                        start_value = 0.902,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_r",
                        start_time = 0.6,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_g",
                        start_time = 0.6,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "square#sprite",
                        property_id = "color_b",
                        start_time = 0.6,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_r",
                        start_value = 0.722,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_g",
                        start_value = 0.741,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_b",
                        start_value = 0.761,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_r",
                        start_time = 0.6,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_g",
                        start_time = 0.6,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "logo#sprite",
                        property_id = "color_b",
                        start_time = 0.6,
                        start_value = 0.6,
                    },
                },
                duration = 1.2,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example2/examples/shapes/shapes.collection",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
