return {
    data = {
        animations = {
            {
                animation_id = "burst",
                animation_keys = {
                    {
                        easing = "linear",
                        key_type = "tween",
                        node_id = "piece_0/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 25.714,
                        key_type = "tween",
                        node_id = "piece_1/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 51.429,
                        key_type = "tween",
                        node_id = "piece_2/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 77.143,
                        key_type = "tween",
                        node_id = "piece_3/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 102.857,
                        key_type = "tween",
                        node_id = "piece_4/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 128.571,
                        key_type = "tween",
                        node_id = "piece_5/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 154.286,
                        key_type = "tween",
                        node_id = "piece_6/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "piece_7/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 205.714,
                        key_type = "tween",
                        node_id = "piece_8/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 231.429,
                        key_type = "tween",
                        node_id = "piece_9/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 257.143,
                        key_type = "tween",
                        node_id = "piece_10/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 282.857,
                        key_type = "tween",
                        node_id = "piece_11/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 308.571,
                        key_type = "tween",
                        node_id = "piece_12/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 334.286,
                        key_type = "tween",
                        node_id = "piece_13/root",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "piece_0/reach",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_0",
                        property_id = "fly",
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 45,
                        key_type = "tween",
                        node_id = "piece_1/reach",
                        property_id = "position_x",
                        start_time = 0.015,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_1",
                        property_id = "fly",
                        start_time = 0.015,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 90,
                        key_type = "tween",
                        node_id = "piece_2/reach",
                        property_id = "position_x",
                        start_time = 0.03,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_2",
                        property_id = "fly",
                        start_time = 0.03,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "piece_3/reach",
                        property_id = "position_x",
                        start_time = 0.045,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_3",
                        property_id = "fly",
                        start_time = 0.045,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 45,
                        key_type = "tween",
                        node_id = "piece_4/reach",
                        property_id = "position_x",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_4",
                        property_id = "fly",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 90,
                        key_type = "tween",
                        node_id = "piece_5/reach",
                        property_id = "position_x",
                        start_time = 0.075,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_5",
                        property_id = "fly",
                        start_time = 0.075,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "piece_6/reach",
                        property_id = "position_x",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_6",
                        property_id = "fly",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 45,
                        key_type = "tween",
                        node_id = "piece_7/reach",
                        property_id = "position_x",
                        start_time = 0.105,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_7",
                        property_id = "fly",
                        start_time = 0.105,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 90,
                        key_type = "tween",
                        node_id = "piece_8/reach",
                        property_id = "position_x",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_8",
                        property_id = "fly",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "piece_9/reach",
                        property_id = "position_x",
                        start_time = 0.135,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_9",
                        property_id = "fly",
                        start_time = 0.135,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 45,
                        key_type = "tween",
                        node_id = "piece_10/reach",
                        property_id = "position_x",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_10",
                        property_id = "fly",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 90,
                        key_type = "tween",
                        node_id = "piece_11/reach",
                        property_id = "position_x",
                        start_time = 0.165,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_11",
                        property_id = "fly",
                        start_time = 0.165,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "piece_12/reach",
                        property_id = "position_x",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_12",
                        property_id = "fly",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 45,
                        key_type = "tween",
                        node_id = "piece_13/reach",
                        property_id = "position_x",
                        start_time = 0.195,
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_13",
                        property_id = "fly",
                        start_time = 0.195,
                    },
                },
                duration = 1.1,
            },
            {
                animation_id = "fountain",
                animation_keys = {
                    {
                        easing = "linear",
                        end_value = 28,
                        key_type = "tween",
                        node_id = "piece_0/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 37.538,
                        key_type = "tween",
                        node_id = "piece_1/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 47.077,
                        key_type = "tween",
                        node_id = "piece_2/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 56.615,
                        key_type = "tween",
                        node_id = "piece_3/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 66.154,
                        key_type = "tween",
                        node_id = "piece_4/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 75.692,
                        key_type = "tween",
                        node_id = "piece_5/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 85.231,
                        key_type = "tween",
                        node_id = "piece_6/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 94.769,
                        key_type = "tween",
                        node_id = "piece_7/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 104.308,
                        key_type = "tween",
                        node_id = "piece_8/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 113.846,
                        key_type = "tween",
                        node_id = "piece_9/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 123.385,
                        key_type = "tween",
                        node_id = "piece_10/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 132.923,
                        key_type = "tween",
                        node_id = "piece_11/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 142.462,
                        key_type = "tween",
                        node_id = "piece_12/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 152,
                        key_type = "tween",
                        node_id = "piece_13/root",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_0",
                        property_id = "arc",
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_1",
                        property_id = "arc",
                        start_time = 0.03,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_2",
                        property_id = "arc",
                        start_time = 0.06,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_3",
                        property_id = "arc",
                        start_time = 0.09,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_4",
                        property_id = "arc",
                        start_time = 0.12,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_5",
                        property_id = "arc",
                        start_time = 0.15,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_6",
                        property_id = "arc",
                        start_time = 0.18,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_7",
                        property_id = "arc",
                        start_time = 0.21,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_8",
                        property_id = "arc",
                        start_time = 0.24,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_9",
                        property_id = "arc",
                        start_time = 0.27,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_10",
                        property_id = "arc",
                        start_time = 0.3,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_11",
                        property_id = "arc",
                        start_time = 0.33,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_12",
                        property_id = "arc",
                        start_time = 0.36,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_13",
                        property_id = "arc",
                        start_time = 0.39,
                    },
                },
                duration = 1.5,
            },
            {
                animation_id = "spiral",
                animation_keys = {
                    {
                        easing = "linear",
                        end_value = 90,
                        key_type = "tween",
                        node_id = "piece_0/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 115.714,
                        key_type = "tween",
                        node_id = "piece_1/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 141.429,
                        key_type = "tween",
                        node_id = "piece_2/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 167.143,
                        key_type = "tween",
                        node_id = "piece_3/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 192.857,
                        key_type = "tween",
                        node_id = "piece_4/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 218.571,
                        key_type = "tween",
                        node_id = "piece_5/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 244.286,
                        key_type = "tween",
                        node_id = "piece_6/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 270,
                        key_type = "tween",
                        node_id = "piece_7/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 295.714,
                        key_type = "tween",
                        node_id = "piece_8/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 321.429,
                        key_type = "tween",
                        node_id = "piece_9/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 347.143,
                        key_type = "tween",
                        node_id = "piece_10/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 372.857,
                        key_type = "tween",
                        node_id = "piece_11/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 398.571,
                        key_type = "tween",
                        node_id = "piece_12/root",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "linear",
                        end_value = 424.286,
                        key_type = "tween",
                        node_id = "piece_13/root",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_0",
                        property_id = "swirl",
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_1",
                        property_id = "swirl",
                        start_time = 0.02,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_2",
                        property_id = "swirl",
                        start_time = 0.04,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_3",
                        property_id = "swirl",
                        start_time = 0.06,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_4",
                        property_id = "swirl",
                        start_time = 0.08,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_5",
                        property_id = "swirl",
                        start_time = 0.1,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_6",
                        property_id = "swirl",
                        start_time = 0.12,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_7",
                        property_id = "swirl",
                        start_time = 0.14,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_8",
                        property_id = "swirl",
                        start_time = 0.16,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_9",
                        property_id = "swirl",
                        start_time = 0.18,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_10",
                        property_id = "swirl",
                        start_time = 0.2,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_11",
                        property_id = "swirl",
                        start_time = 0.22,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_12",
                        property_id = "swirl",
                        start_time = 0.24,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "piece_13",
                        property_id = "swirl",
                        start_time = 0.26,
                    },
                },
                duration = 1.4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/confetti/confetti.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
                piece_0 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_1 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_10 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_11 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_12 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_13 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_2 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_3 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_4 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_5 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_6 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_7 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_8 = require("example.examples.confetti.confetti_piece_panthera"),
                piece_9 = require("example.examples.confetti.confetti_piece_panthera"),
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}