return {
    data = {
        animations = {
            {
                animation_id = "burst",
                animation_keys = {
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 300,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = -540,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 149.69,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "position_y",
                        start_time = 0.015,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 310.834,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "position_x",
                        start_time = 0.015,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = 540,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.015,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 243.161,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "position_x",
                        start_time = 0.03,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 304.914,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "position_y",
                        start_time = 0.03,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = -540,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.03,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 66.756,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "position_x",
                        start_time = 0.045,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 292.478,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "position_y",
                        start_time = 0.045,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = 540,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.045,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -76.77,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "position_x",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 336.35,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "position_y",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = -540,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -243.161,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "position_x",
                        start_time = 0.075,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 304.914,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "position_y",
                        start_time = 0.075,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = 540,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.075,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -270.291,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "position_x",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 130.165,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "position_y",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = -540,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -345,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "position_x",
                        start_time = 0.105,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "position_y",
                        start_time = 0.105,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = 540,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.105,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -351.378,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "position_x",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -169.215,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "position_y",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = -540,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -234.549,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "position_y",
                        start_time = 0.135,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -187.047,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "position_x",
                        start_time = 0.135,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = 540,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "rotation_z",
                        start_time = 0.135,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -336.35,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "position_y",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -76.77,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "position_x",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = -540,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "rotation_z",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -380.222,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "position_y",
                        start_time = 0.165,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 86.783,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "position_x",
                        start_time = 0.165,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = 540,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "rotation_z",
                        start_time = 0.165,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -234.549,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "position_y",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 187.047,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "position_x",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = -540,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "rotation_z",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -149.69,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "position_y",
                        start_time = 0.195,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 310.834,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "position_x",
                        start_time = 0.195,
                    },
                    {
                        duration = 0.9,
                        easing = "outcubic",
                        end_value = 540,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "rotation_z",
                        start_time = 0.195,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "color_a",
                        start_time = 0.45,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "color_a",
                        start_time = 0.465,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "color_a",
                        start_time = 0.48,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "color_a",
                        start_time = 0.495,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "color_a",
                        start_time = 0.51,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "color_a",
                        start_time = 0.525,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "color_a",
                        start_time = 0.54,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "color_a",
                        start_time = 0.555,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "color_a",
                        start_time = 0.57,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "color_a",
                        start_time = 0.585,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "color_a",
                        start_time = 0.6,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "color_a",
                        start_time = 0.615,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "color_a",
                        start_time = 0.63,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "color_a",
                        start_time = 0.645,
                        start_value = 1,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "fountain",
                animation_keys = {
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "position_y",
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = -300,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = -299,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 310,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "position_y",
                        start_time = 0.03,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = -253,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "position_x",
                        start_time = 0.03,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.03,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "position_y",
                        start_time = 0.06,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = -300,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.06,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = -207,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "position_x",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 410,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "position_y",
                        start_time = 0.09,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = -161,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "position_x",
                        start_time = 0.09,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "position_y",
                        start_time = 0.12,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = -300,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.12,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = -115,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "position_x",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 310,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "position_y",
                        start_time = 0.15,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = -69,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "position_x",
                        start_time = 0.15,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "position_y",
                        start_time = 0.18,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = -300,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.18,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = -23,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "position_x",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 410,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "position_y",
                        start_time = 0.21,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = 23,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "position_x",
                        start_time = 0.21,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.21,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "position_y",
                        start_time = 0.24,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = -300,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_time = 0.24,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = 69,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "position_x",
                        start_time = 0.24,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 310,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "position_y",
                        start_time = 0.27,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = 115,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "position_x",
                        start_time = 0.27,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "rotation_z",
                        start_time = 0.27,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "position_y",
                        start_time = 0.3,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = -300,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "rotation_z",
                        start_time = 0.3,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = 161,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "position_x",
                        start_time = 0.3,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 410,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "position_y",
                        start_time = 0.33,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = 207,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "position_x",
                        start_time = 0.33,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "rotation_z",
                        start_time = 0.33,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "position_y",
                        start_time = 0.36,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = -300,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "rotation_z",
                        start_time = 0.36,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = 253,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "position_x",
                        start_time = 0.36,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 310,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "position_y",
                        start_time = 0.39,
                    },
                    {
                        duration = 1.1,
                        easing = "outsine",
                        end_value = 299,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "position_x",
                        start_time = 0.39,
                    },
                    {
                        duration = 1.1,
                        easing = "linear",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "rotation_z",
                        start_time = 0.39,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "position_y",
                        start_time = 0.45,
                        start_value = 260,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "position_y",
                        start_time = 0.48,
                        start_value = 310,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "position_y",
                        start_time = 0.51,
                        start_value = 360,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "position_y",
                        start_time = 0.54,
                        start_value = 410,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "position_y",
                        start_time = 0.57,
                        start_value = 260,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "position_y",
                        start_time = 0.6,
                        start_value = 310,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "position_y",
                        start_time = 0.63,
                        start_value = 360,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "position_y",
                        start_time = 0.66,
                        start_value = 410,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "position_y",
                        start_time = 0.69,
                        start_value = 260,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "position_y",
                        start_time = 0.72,
                        start_value = 310,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "color_a",
                        start_time = 0.75,
                        start_value = 1,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "position_y",
                        start_time = 0.75,
                        start_value = 360,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "color_a",
                        start_time = 0.78,
                        start_value = 1,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "position_y",
                        start_time = 0.78,
                        start_value = 410,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "color_a",
                        start_time = 0.81,
                        start_value = 1,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "position_y",
                        start_time = 0.81,
                        start_value = 260,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "color_a",
                        start_time = 0.84,
                        start_value = 1,
                    },
                    {
                        duration = 0.65,
                        easing = "insine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "position_y",
                        start_time = 0.84,
                        start_value = 310,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "color_a",
                        start_time = 0.87,
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "color_a",
                        start_time = 0.9,
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "color_a",
                        start_time = 0.93,
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "color_a",
                        start_time = 0.96,
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "color_a",
                        start_time = 0.99,
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "color_a",
                        start_time = 1.02,
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "color_a",
                        start_time = 1.05,
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "color_a",
                        start_time = 1.08,
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "color_a",
                        start_time = 1.11,
                        start_value = 1,
                    },
                    {
                        duration = 0.35,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "color_a",
                        start_time = 1.14,
                        start_value = 1,
                    },
                },
                duration = 1.5,
            },
            {
                animation_id = "spiral",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "position_y",
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -78.099,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "position_x",
                        start_time = 0.02,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 162.174,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "position_y",
                        start_time = 0.02,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.02,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -140.73,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "position_x",
                        start_time = 0.04,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 112.228,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "position_y",
                        start_time = 0.04,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.04,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -175.487,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "position_x",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 40.054,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "position_y",
                        start_time = 0.06,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -175.487,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "position_x",
                        start_time = 0.08,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -40.054,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "position_y",
                        start_time = 0.08,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.08,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -140.73,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "position_x",
                        start_time = 0.1,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -112.228,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "position_y",
                        start_time = 0.1,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.1,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -162.174,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "position_y",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -78.099,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "position_x",
                        start_time = 0.12,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -180,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "position_y",
                        start_time = 0.14,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "position_x",
                        start_time = 0.14,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.14,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -162.174,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "position_y",
                        start_time = 0.16,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 78.099,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "position_x",
                        start_time = 0.16,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_time = 0.16,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -112.228,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "position_y",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 140.73,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "position_x",
                        start_time = 0.18,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "rotation_z",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -40.054,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "position_y",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 175.487,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "position_x",
                        start_time = 0.2,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "rotation_z",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 40.054,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "position_y",
                        start_time = 0.22,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 175.487,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "position_x",
                        start_time = 0.22,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "rotation_z",
                        start_time = 0.22,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 112.228,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "position_y",
                        start_time = 0.24,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 140.73,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "position_x",
                        start_time = 0.24,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "rotation_z",
                        start_time = 0.24,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 78.099,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "position_x",
                        start_time = 0.26,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 162.174,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "position_y",
                        start_time = 0.26,
                    },
                    {
                        duration = 1.1,
                        easing = "inoutsine",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "rotation_z",
                        start_time = 0.26,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -340,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "position_x",
                        start_time = 0.5,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 180,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -306.329,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "position_x",
                        start_time = 0.52,
                        start_value = -78.099,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -147.52,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "position_y",
                        start_time = 0.52,
                        start_value = 162.174,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -265.823,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "position_y",
                        start_time = 0.54,
                        start_value = 112.228,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -211.987,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "position_x",
                        start_time = 0.54,
                        start_value = -140.73,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -331.475,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "position_y",
                        start_time = 0.56,
                        start_value = 40.054,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -75.657,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "position_x",
                        start_time = 0.56,
                        start_value = -175.487,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -331.475,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "position_y",
                        start_time = 0.58,
                        start_value = -40.054,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 75.657,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "position_x",
                        start_time = 0.58,
                        start_value = -175.487,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -265.823,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "position_y",
                        start_time = 0.6,
                        start_value = -112.228,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 211.987,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "position_x",
                        start_time = 0.6,
                        start_value = -140.73,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -147.52,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "position_y",
                        start_time = 0.62,
                        start_value = -162.174,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 306.329,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "position_x",
                        start_time = 0.62,
                        start_value = -78.099,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "position_y",
                        start_time = 0.64,
                        start_value = -180,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "position_x",
                        start_time = 0.64,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 147.52,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "position_y",
                        start_time = 0.66,
                        start_value = -162.174,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 306.329,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "position_x",
                        start_time = 0.66,
                        start_value = 78.099,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 211.987,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "position_x",
                        start_time = 0.68,
                        start_value = 140.73,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 265.823,
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "position_y",
                        start_time = 0.68,
                        start_value = -112.228,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 75.657,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "position_x",
                        start_time = 0.7,
                        start_value = 175.487,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 331.475,
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "position_y",
                        start_time = 0.7,
                        start_value = -40.054,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -75.657,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "position_x",
                        start_time = 0.72,
                        start_value = 175.487,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 331.475,
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "position_y",
                        start_time = 0.72,
                        start_value = 40.054,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -211.987,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "position_x",
                        start_time = 0.74,
                        start_value = 140.73,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 265.823,
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "position_y",
                        start_time = 0.74,
                        start_value = 112.228,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -306.329,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "position_x",
                        start_time = 0.76,
                        start_value = 78.099,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 147.52,
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "position_y",
                        start_time = 0.76,
                        start_value = 162.174,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "color_a",
                        start_time = 0.8,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "color_a",
                        start_time = 0.82,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "color_a",
                        start_time = 0.84,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "color_a",
                        start_time = 0.86,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "color_a",
                        start_time = 0.88,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "color_a",
                        start_time = 0.9,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "color_a",
                        start_time = 0.92,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "color_a",
                        start_time = 0.94,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "color_a",
                        start_time = 0.96,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_9",
                        property_id = "color_a",
                        start_time = 0.98,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_10",
                        property_id = "color_a",
                        start_time = 1,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_11",
                        property_id = "color_a",
                        start_time = 1.02,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_12",
                        property_id = "color_a",
                        start_time = 1.04,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "piece_13",
                        property_id = "color_a",
                        start_time = 1.06,
                        start_value = 1,
                    },
                },
                duration = 1.4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/confetti/confetti.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}