return {
    data = {
        animations = {
            {
                animation_id = "greet",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "avatar#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "avatar#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "avatar#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_a",
                        start_value = 0.25,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.25,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_a",
                        start_time = 0.4,
                        start_value = 0.7,
                    },
                    {
                        data = "Components",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "avatar#label",
                        property_id = "text",
                        start_data = "Components",
                    },
                    {
                        data = "one game object",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "avatar#label",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.45,
                    },
                    {
                        data = "three components",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "avatar#label",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.9,
                    },
                    {
                        data = "Components",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "avatar#label",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.35,
                    },
                    {
                        duration = 0.3,
                        easing = "outback",
                        end_value = 1.15,
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "scale_x",
                        start_time = 0.3,
                        start_value = 1.15,
                    },
                    {
                        duration = 0.3,
                        easing = "outback",
                        end_value = 1.15,
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "scale_y",
                        start_time = 0.3,
                        start_value = 1.15,
                    },
                },
                duration = 1.8,
            },
            {
                animation_id = "glow",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "avatar#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "avatar#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "avatar#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_r",
                        start_time = 0.5,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_g",
                        start_time = 0.5,
                        start_value = 0.502,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_b",
                        start_time = 0.5,
                        start_value = 0.902,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "avatar#label",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "avatar#label",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "avatar#label",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "avatar#label",
                        property_id = "color_r",
                        start_time = 0.5,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "avatar#label",
                        property_id = "color_g",
                        start_time = 0.5,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "avatar#label",
                        property_id = "color_b",
                        start_time = 0.5,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_a",
                        start_value = 0.25,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.25,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_a",
                        start_time = 0.5,
                        start_value = 0.9,
                    },
                },
                duration = 1.1,
            },
            {
                animation_id = "hop",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "avatar#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "avatar#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "avatar#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.25,
                        key_type = "tween",
                        node_id = "avatar#glow",
                        property_id = "color_a",
                        start_value = 0.25,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.45,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "position_y",
                        start_time = 0.35,
                        start_value = 180,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 20,
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.5,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "avatar",
                        property_id = "rotation_z",
                        start_time = 0.4,
                        start_value = 20,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/components/avatar.go",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
