return {
    data = {
        animations = {
            {
                animation_id = "flip",
                animation_keys = {
                    {
                        duration = 0.23,
                        easing = "outsine",
                        end_value = 45,
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_y",
                    },
                    {
                        duration = 1,
                        easing = "outcubic",
                        end_value = -70,
                        key_type = "tween",
                        node_id = "dot",
                        property_id = "position_x",
                    },
                    {
                        duration = 1,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_x",
                        start_value = 70,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 70,
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_x",
                        start_value = -70,
                    },
                    {
                        duration = 0.77,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_y",
                        start_time = 0.23,
                        start_value = 45,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "bounce",
                animation_keys = {
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 55,
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 75,
                        key_type = "tween",
                        node_id = "dot",
                        property_id = "position_y",
                        start_time = 0.1,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -55,
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_y",
                        start_time = 0.2,
                        start_value = 55,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 95,
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_y",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -55,
                        key_type = "tween",
                        node_id = "dot",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = 75,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -55,
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_y",
                        start_time = 0.4,
                        start_value = 95,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_y",
                        start_time = 0.4,
                        start_value = -55,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "dot",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = -55,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_y",
                        start_time = 0.6,
                        start_value = -55,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "what",
                animation_keys = {
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = -200,
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_x",
                        start_value = -70,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 125,
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.375,
                        easing = "outsine",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "dot",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.375,
                        easing = "outsine",
                        end_value = 190,
                        key_type = "tween",
                        node_id = "dot",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 150,
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 155,
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_x",
                        start_value = 70,
                    },
                    {
                        duration = 0.7,
                        easing = "outback",
                        end_value = -70,
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_x",
                        start_time = 0.3,
                        start_value = -200,
                    },
                    {
                        duration = 0.7,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "dot1",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = 125,
                    },
                    {
                        duration = 0.62,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "dot",
                        property_id = "position_x",
                        start_time = 0.38,
                        start_value = -10,
                    },
                    {
                        duration = 0.62,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "dot",
                        property_id = "position_y",
                        start_time = 0.38,
                        start_value = 190,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 150,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 70,
                        key_type = "tween",
                        node_id = "dot2",
                        property_id = "position_x",
                        start_time = 0.5,
                        start_value = 155,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/example_template_animations/templates/dots.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}