return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_value = 1.5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_value = 1.5,
                    },
                    {
                        duration = 0.51,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_r",
                        start_value = 0.8,
                    },
                    {
                        duration = 0.51,
                        easing = "outsine",
                        end_value = 0.679,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_b",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.51,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_g",
                        start_value = 0.502,
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots",
                        property_id = "flip",
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 2,
                    },
                    {
                        duration = 0.49,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_g",
                        start_time = 0.51,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.49,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_b",
                        start_time = 0.51,
                        start_value = 0.679,
                    },
                    {
                        duration = 0.49,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_r",
                        start_time = 0.51,
                        start_value = 0.502,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "/example/example_template_animations/templates/square_animation.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
                dots = require("example.example_template_animations.templates.dots_panthera"),
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}