return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_value = 1.5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_value = 1.5,
                    },
                    {
                        duration = 0.51,
                        easing = "outsine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_r",
                        start_value = 0.8,
                    },
                    {
                        duration = 0.51,
                        easing = "outsine",
                        end_value = 0.68,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_b",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.51,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_g",
                        start_value = 0.502,
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots",
                        property_id = "flip",
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 2,
                    },
                    {
                        duration = 0.49,
                        easing = "outsine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_g",
                        start_time = 0.51,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.49,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_b",
                        start_time = 0.51,
                        start_value = 0.68,
                    },
                    {
                        duration = 0.49,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "square",
                        property_id = "color_r",
                        start_time = 0.51,
                        start_value = 0.5,
                    },
                },
                duration = 1,
                formatted_duration = "1.0",
            },
            {
                animation_id = "bounced",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots",
                        property_id = "bounce",
                    },
                    {
                        duration = 0.39,
                        easing = "linear",
                        key_type = "animation",
                        node_id = "dots",
                        property_id = "flip",
                        start_time = 0.43,
                    },
                    {
                        duration = 0.4,
                        easing = "outbounce",
                        key_type = "animation",
                        node_id = "dots",
                        property_id = "flip",
                        start_time = 1,
                    },
                },
                duration = 1.4,
                formatted_duration = "1.4",
            },
            {
                animation_id = "solar",
                animation_keys = {
                    {
                        duration = 0.53,
                        easing = "outsine",
                        end_value = -75,
                        key_type = "tween",
                        node_id = "dots/dot1",
                        property_id = "position_x",
                        start_value = -70,
                    },
                    {
                        duration = 0.53,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "dots/dot1",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.53,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "dots/dot1",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.53,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "dots/dot2",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.53,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "dots/dot2",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.53,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.53,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.53,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.53,
                        easing = "outsine",
                        end_value = 75,
                        key_type = "tween",
                        node_id = "dots/dot2",
                        property_id = "position_x",
                        start_value = 70,
                    },
                    {
                        duration = 0.13,
                        easing = "outsine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "scale_x",
                        start_time = 0.53,
                        start_value = 2,
                    },
                    {
                        duration = 0.13,
                        easing = "outsine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "scale_y",
                        start_time = 0.53,
                        start_value = 2,
                    },
                    {
                        duration = 0.23,
                        easing = "outsine",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "dots/dot1",
                        property_id = "position_x",
                        start_time = 0.53,
                        start_value = -75,
                    },
                    {
                        duration = 0.23,
                        easing = "outsine",
                        end_value = 10,
                        key_type = "tween",
                        node_id = "dots/dot2",
                        property_id = "position_x",
                        start_time = 0.53,
                        start_value = 75,
                    },
                    {
                        duration = 0.79,
                        easing = "outback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "scale_x",
                        start_time = 0.65,
                        start_value = 0.5,
                    },
                    {
                        duration = 0.79,
                        easing = "outback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "scale_y",
                        start_time = 0.65,
                        start_value = 0.5,
                    },
                    {
                        data = "example/ui_rect_round_64",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "dots/dot",
                        property_id = "texture",
                        start_data = "example/ui_rect_round_16",
                        start_time = 0.66,
                    },
                    {
                        easing = "outsine",
                        end_value = 64,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "slice9_bottom",
                        start_time = 0.66,
                        start_value = 16,
                    },
                    {
                        easing = "outsine",
                        end_value = 64,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "slice9_left",
                        start_time = 0.66,
                        start_value = 16,
                    },
                    {
                        easing = "outsine",
                        end_value = 64,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "slice9_right",
                        start_time = 0.66,
                        start_value = 16,
                    },
                    {
                        easing = "outsine",
                        end_value = 64,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "slice9_top",
                        start_time = 0.66,
                        start_value = 16,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "dots/dot1",
                        property_id = "color_a",
                        start_time = 0.83,
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "dots/dot2",
                        property_id = "color_a",
                        start_time = 0.83,
                        start_value = 1,
                    },
                    {
                        duration = 0.51,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "color_a",
                        start_time = 0.9,
                        start_value = 1,
                    },
                    {
                        duration = 0.38,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "position_x",
                        start_time = 1.62,
                        start_value = 1,
                    },
                    {
                        duration = 0.38,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot1",
                        property_id = "scale_x",
                        start_time = 1.62,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.38,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot1",
                        property_id = "scale_y",
                        start_time = 1.62,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.38,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot2",
                        property_id = "scale_x",
                        start_time = 1.62,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.38,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot2",
                        property_id = "scale_y",
                        start_time = 1.62,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.32,
                        easing = "outsine",
                        end_value = -70,
                        key_type = "tween",
                        node_id = "dots/dot1",
                        property_id = "position_x",
                        start_time = 1.68,
                        start_value = -10,
                    },
                    {
                        duration = 0.32,
                        easing = "outsine",
                        end_value = 70,
                        key_type = "tween",
                        node_id = "dots/dot2",
                        property_id = "position_x",
                        start_time = 1.68,
                        start_value = 10,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot1",
                        property_id = "color_a",
                        start_time = 1.7,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot2",
                        property_id = "color_a",
                        start_time = 1.7,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "color_a",
                        start_time = 1.85,
                    },
                    {
                        duration = 0.14,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "scale_x",
                        start_time = 1.86,
                        start_value = 3,
                    },
                    {
                        duration = 0.14,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "dots/dot",
                        property_id = "scale_y",
                        start_time = 1.86,
                        start_value = 3,
                    },
                },
                duration = 2,
                formatted_duration = "2.0",
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "example/example_template_animations/templates/square_animation.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
                dots = require("example.example_template_animations.templates.dots_panthera"),
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}