return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        data = "Position",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "text",
                        start_data = "Test",
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.23,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_b",
                        start_value = 0.106,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.23,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_g",
                        start_value = 0.106,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.41,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_r",
                        start_value = 0.106,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 100,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = -100,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "position_y",
                        start_time = 0.5,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.27,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_r",
                        start_time = 0.5,
                        start_value = 0.41,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.41,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_g",
                        start_time = 0.5,
                        start_value = 0.23,
                    },
                    {
                        duration = 4,
                        easing = "outsine",
                        end_value = 0.41,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_b",
                        start_time = 0.5,
                        start_value = 0.23,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "position_x",
                        start_time = 1,
                        start_value = 100,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "position_y",
                        start_time = 1,
                        start_value = -100,
                    },
                    {
                        data = "Rotation",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "text",
                        start_data = "Position",
                        start_time = 1.5,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = -90,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "rotation_z",
                        start_time = 1.5,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 90,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "rotation_z",
                        start_time = 2,
                        start_value = -90,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "rotation_z",
                        start_time = 2.5,
                        start_value = 90,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.23,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_r",
                        start_time = 2.5,
                        start_value = 0.27,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.35,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_g",
                        start_time = 2.5,
                        start_value = 0.41,
                    },
                    {
                        data = "Rotation X/Y",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "text",
                        start_data = "Rotation",
                        start_time = 3,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "rotation_x",
                        start_time = 3,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "rotation_y",
                        start_time = 3,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "rotation_x",
                        start_time = 3.5,
                        start_value = 40,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "rotation_y",
                        start_time = 3.5,
                        start_value = 40,
                    },
                    {
                        data = "Scale",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "text",
                        start_data = "Rotation X/Y",
                        start_time = 4,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "scale_x",
                        start_time = 4,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "scale_y",
                        start_time = 4,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "scale_x",
                        start_time = 4.5,
                        start_value = 1.6,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "scale_y",
                        start_time = 4.5,
                        start_value = 1.6,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.23,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_g",
                        start_time = 4.5,
                        start_value = 0.35,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.35,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_r",
                        start_time = 4.5,
                        start_value = 0.23,
                    },
                    {
                        duration = 4,
                        easing = "outsine",
                        end_value = 0.29,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_b",
                        start_time = 4.5,
                        start_value = 0.41,
                    },
                    {
                        data = "manual",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "image",
                        property_id = "size_mode",
                        start_data = "auto",
                        start_time = 5,
                    },
                    {
                        data = "Size",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "text",
                        start_data = "Scale",
                        start_time = 5,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 228,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_y",
                        start_time = 5,
                        start_value = 128,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 628,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_x",
                        start_time = 5,
                        start_value = 128,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 150,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_x",
                        start_time = 5.5,
                        start_value = 628,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 150,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_y",
                        start_time = 5.5,
                        start_value = 228,
                    },
                    {
                        data = "example/ui_circle",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "image",
                        property_id = "texture",
                        start_data = "example/panthera",
                        start_time = 6,
                    },
                    {
                        data = "Image & Color",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "text",
                        start_data = "Size",
                        start_time = 6,
                    },
                    {
                        easing = "outsine",
                        end_value = 0.31,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_g",
                        start_time = 6,
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        end_value = 0.62,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_r",
                        start_time = 6,
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_b",
                        start_time = 6,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.31,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_b",
                        start_time = 6,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.41,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_r",
                        start_time = 6,
                        start_value = 0.62,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_g",
                        start_time = 6,
                        start_value = 0.31,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.31,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_g",
                        start_time = 6.5,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.56,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_b",
                        start_time = 6.5,
                        start_value = 0.31,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_r",
                        start_time = 6.5,
                        start_value = 0.41,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.41,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_r",
                        start_time = 6.5,
                        start_value = 0.35,
                    },
                    {
                        duration = 3.5,
                        easing = "outsine",
                        end_value = 0.11,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_g",
                        start_time = 6.5,
                        start_value = 0.23,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_b",
                        start_time = 7,
                        start_value = 0.56,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_g",
                        start_time = 7,
                        start_value = 0.31,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_r",
                        start_time = 7,
                        start_value = 0.8,
                    },
                    {
                        data = "example/panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "image",
                        property_id = "texture",
                        start_data = "example/ui_circle",
                        start_time = 7.5,
                    },
                    {
                        data = "Opacity",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "text",
                        start_data = "Image & Color",
                        start_time = 7.5,
                    },
                    {
                        easing = "outsine",
                        end_value = 128,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_x",
                        start_time = 7.5,
                        start_value = 150,
                    },
                    {
                        easing = "outsine",
                        end_value = 128,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_y",
                        start_time = 7.5,
                        start_value = 150,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_a",
                        start_time = 7.5,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "color_a",
                        start_time = 8,
                    },
                    {
                        data = "Slice9",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text",
                        property_id = "text",
                        start_data = "Opacity",
                        start_time = 8.5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 32,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_bottom",
                        start_time = 8.5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 32,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_left",
                        start_time = 8.5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 32,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_right",
                        start_time = 8.5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 32,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_top",
                        start_time = 8.5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 428,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_x",
                        start_time = 8.5,
                        start_value = 128,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 428,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_y",
                        start_time = 8.5,
                        start_value = 128,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 0.11,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_b",
                        start_time = 8.5,
                        start_value = 0.29,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 0.11,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "color_r",
                        start_time = 8.5,
                        start_value = 0.41,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_right",
                        start_time = 9,
                        start_value = 32,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_top",
                        start_time = 9,
                        start_value = 32,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 64,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_bottom",
                        start_time = 9,
                        start_value = 32,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 64,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_left",
                        start_time = 9,
                        start_value = 32,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 128,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_x",
                        start_time = 9,
                        start_value = 428,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 128,
                        key_type = "tween",
                        node_id = "image",
                        property_id = "size_y",
                        start_time = 9,
                        start_value = 428,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_bottom",
                        start_time = 9.5,
                        start_value = 64,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "image",
                        property_id = "slice9_left",
                        start_time = 9.5,
                        start_value = 64,
                    },
                },
                duration = 10,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                position = 50,
                rotation = 45,
                scale = 0.1,
                size = 50,
                time = 0.5,
            },
            gui_path = "example/example_test_all_properties/example_test_all_properties.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}