return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.21,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.36,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 1.27,
                        easing = "outsine",
                        end_value = -1,
                        key_type = "tween",
                        node_id = "go#sprite",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 55,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 0.72,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 0.36,
                    },
                    {
                        duration = 0.93,
                        easing = "outsine",
                        end_value = 0.44,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 0.21,
                    },
                    {
                        duration = 0.48,
                        easing = "outsine",
                        end_value = 0.21,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_time = 1.15,
                        start_value = 0.72,
                    },
                    {
                        duration = 0.95,
                        easing = "outsine",
                        end_value = 0.74,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_time = 1.15,
                        start_value = 1,
                    },
                    {
                        duration = 0.71,
                        easing = "outsine",
                        end_value = -1,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_x",
                        start_time = 1.5,
                        start_value = 1.5,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "go",
                        property_id = "position_y",
                        start_time = 1.5,
                        start_value = 55,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_y",
                        start_time = 1.5,
                        start_value = 1.5,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_b",
                        start_time = 1.63,
                        start_value = 0.44,
                    },
                    {
                        duration = 0.75,
                        easing = "outsine",
                        end_value = 0.57,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_time = 1.63,
                        start_value = 0.21,
                    },
                    {
                        duration = 0.28,
                        easing = "outsine",
                        end_value = 0.21,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_time = 2.1,
                        start_value = 0.74,
                    },
                    {
                        duration = 0.41,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go#sprite",
                        property_id = "scale_x",
                        start_time = 2.15,
                        start_value = -1,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_x",
                        start_time = 2.21,
                        start_value = -1,
                    },
                    {
                        duration = 0.36,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_time = 2.38,
                        start_value = 0.21,
                    },
                    {
                        duration = 0.36,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_time = 2.38,
                        start_value = 0.57,
                    },
                    {
                        data = "Hello!",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "go#label",
                        property_id = "text",
                        start_data = "Hello",
                        start_time = 2.42,
                    },
                    {
                        duration = 0.44,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_x",
                        start_time = 2.56,
                        start_value = 1.5,
                    },
                    {
                        data = "Hello",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "go#label",
                        property_id = "text",
                        start_data = "Hello!",
                        start_time = 2.99,
                    },
                },
                duration = 3,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
            {
                blend_mode = "alpha",
                clipping_mode = "none",
                clipping_visible = true,
                color_a = 1,
                color_b = 1,
                color_g = 1,
                color_r = 1,
                enabled = true,
                inherit_alpha = true,
                node_id = "go_2",
                node_index = 1,
                node_type = "box",
                pivot = "pivot_center",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_mode = "auto",
                size_x = 200,
                size_y = 100,
            },
            {
                blend_mode = "alpha",
                clipping_mode = "none",
                clipping_visible = true,
                color_a = 1,
                color_b = 1,
                color_g = 1,
                color_r = 1,
                enabled = true,
                inherit_alpha = true,
                node_id = "go_2#sprite",
                node_index = 2,
                node_type = "box",
                parent = "go_2",
                pivot = "pivot_center",
                position_z = -0.01,
                scale_x = 3,
                scale_y = 3,
                scale_z = 1,
                size_mode = "auto",
                size_x = 150,
                size_y = 150,
                texture = "example/ui_circle",
                visible = true,
            },
            {
                blend_mode = "alpha",
                clipping_mode = "none",
                clipping_visible = true,
                color_a = 1,
                color_b = 1,
                color_g = 1,
                color_r = 1,
                enabled = true,
                inherit_alpha = true,
                node_id = "go",
                node_index = 3,
                node_type = "box",
                pivot = "pivot_center",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_mode = "auto",
                size_x = 200,
                size_y = 100,
            },
            {
                blend_mode = "alpha",
                clipping_mode = "none",
                clipping_visible = true,
                color_a = 1,
                color_b = 1,
                color_g = 1,
                color_r = 1,
                enabled = true,
                inherit_alpha = true,
                node_id = "go#sprite",
                node_index = 4,
                node_type = "box",
                parent = "go",
                pivot = "pivot_center",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_mode = "auto",
                size_x = 128,
                size_y = 128,
                texture = "example/panthera",
                visible = true,
            },
            {
                blend_mode = "alpha",
                clipping_mode = "none",
                clipping_visible = true,
                color_a = 1,
                enabled = true,
                inherit_alpha = true,
                node_id = "go#label",
                node_index = 5,
                node_type = "text",
                parent = "go",
                pivot = "pivot_center",
                position_y = -81,
                position_z = -0.01,
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_mode = "auto",
                size_x = 200,
                size_y = 100,
                text = "Hello",
                visible = true,
            },
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}