return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.21,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.36,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 1.27,
                        easing = "outsine",
                        end_value = -1,
                        key_type = "tween",
                        node_id = "go#sprite",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 55,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 0.72,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 0.36,
                    },
                    {
                        duration = 0.93,
                        easing = "outsine",
                        end_value = 0.44,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 0.21,
                    },
                    {
                        duration = 0.48,
                        easing = "outsine",
                        end_value = 0.21,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_time = 1.15,
                        start_value = 0.72,
                    },
                    {
                        duration = 0.95,
                        easing = "outsine",
                        end_value = 0.74,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_time = 1.15,
                        start_value = 1,
                    },
                    {
                        duration = 0.71,
                        easing = "outsine",
                        end_value = -1,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_x",
                        start_time = 1.5,
                        start_value = 1.5,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "go",
                        property_id = "position_y",
                        start_time = 1.5,
                        start_value = 55,
                    },
                    {
                        duration = 1.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_y",
                        start_time = 1.5,
                        start_value = 1.5,
                    },
                    {
                        data = "example/ui_rect_round_32",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "go#sprite",
                        property_id = "texture",
                        start_data = "example/panthera",
                        start_time = 1.61,
                    },
                    {
                        duration = 0.47,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_b",
                        start_time = 1.63,
                        start_value = 0.44,
                    },
                    {
                        duration = 0.75,
                        easing = "outsine",
                        end_value = 0.57,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_time = 1.63,
                        start_value = 0.21,
                    },
                    {
                        duration = 0.28,
                        easing = "outsine",
                        end_value = 0.21,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_time = 2.1,
                        start_value = 0.74,
                    },
                    {
                        duration = 0.41,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go#sprite",
                        property_id = "scale_x",
                        start_time = 2.15,
                        start_value = -1,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_x",
                        start_time = 2.21,
                        start_value = -1,
                    },
                    {
                        duration = 0.36,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_g",
                        start_time = 2.38,
                        start_value = 0.21,
                    },
                    {
                        duration = 0.36,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go_2#sprite",
                        property_id = "color_r",
                        start_time = 2.38,
                        start_value = 0.57,
                    },
                    {
                        data = "Hello!",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "go#label",
                        property_id = "text",
                        start_data = "Hello",
                        start_time = 2.42,
                    },
                    {
                        duration = 0.44,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "go",
                        property_id = "scale_x",
                        start_time = 2.56,
                        start_value = 1.5,
                    },
                    {
                        data = "Hello",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "go#label",
                        property_id = "text",
                        start_data = "Hello!",
                        start_time = 2.99,
                    },
                },
                duration = 3,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "example/example_go/example_go.collection",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}