return {
    data = {
        animations = {
            {
                animation_id = "scroll",
                animation_keys = {
                    {
                        duration = 2,
                        easing = "linear",
                        end_value = -1200,
                        key_type = "tween",
                        node_id = "back_0",
                        property_id = "position_x",
                    },
                    {
                        duration = 2,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "back_1",
                        property_id = "position_x",
                        start_value = 1200,
                    },
                    {
                        duration = 2,
                        easing = "linear",
                        end_value = -800,
                        key_type = "tween",
                        node_id = "mid_0",
                        property_id = "position_x",
                    },
                    {
                        duration = 2,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "mid_1",
                        property_id = "position_x",
                        start_value = 800,
                    },
                    {
                        duration = 2,
                        easing = "linear",
                        end_value = -500,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "position_x",
                    },
                    {
                        duration = 2,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "position_x",
                        start_value = 500,
                    },
                },
                duration = 2,
            },
            {
                animation_id = "night",
                animation_keys = {
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "sun",
                        property_id = "color_r",
                        start_value = 0.722,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "sun",
                        property_id = "color_g",
                        start_value = 0.741,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "sun",
                        property_id = "color_b",
                        start_value = 0.761,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.35,
                        key_type = "tween",
                        node_id = "sun",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 0.722,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.38,
                        key_type = "tween",
                        node_id = "sun",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 0.741,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.52,
                        key_type = "tween",
                        node_id = "sun",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 0.761,
                    },
                    {
                        duration = 0.7,
                        easing = "inoutsine",
                        end_value = -60,
                        key_type = "tween",
                        node_id = "sun",
                        property_id = "position_y",
                        start_value = 190,
                    },
                    {
                        duration = 0.7,
                        easing = "inoutsine",
                        end_value = 190,
                        key_type = "tween",
                        node_id = "sun",
                        property_id = "position_y",
                        start_time = 0.7,
                        start_value = -60,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.16,
                        key_type = "tween",
                        node_id = "back_0",
                        property_id = "color_r",
                        start_value = 0.24,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.17,
                        key_type = "tween",
                        node_id = "back_0",
                        property_id = "color_g",
                        start_value = 0.26,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.26,
                        key_type = "tween",
                        node_id = "back_0",
                        property_id = "color_b",
                        start_value = 0.32,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.24,
                        key_type = "tween",
                        node_id = "back_0",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 0.16,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.26,
                        key_type = "tween",
                        node_id = "back_0",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 0.17,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.32,
                        key_type = "tween",
                        node_id = "back_0",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 0.26,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.16,
                        key_type = "tween",
                        node_id = "back_1",
                        property_id = "color_r",
                        start_value = 0.24,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.17,
                        key_type = "tween",
                        node_id = "back_1",
                        property_id = "color_g",
                        start_value = 0.26,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.26,
                        key_type = "tween",
                        node_id = "back_1",
                        property_id = "color_b",
                        start_value = 0.32,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.24,
                        key_type = "tween",
                        node_id = "back_1",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 0.16,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.26,
                        key_type = "tween",
                        node_id = "back_1",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 0.17,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.32,
                        key_type = "tween",
                        node_id = "back_1",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 0.26,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.2,
                        key_type = "tween",
                        node_id = "mid_0",
                        property_id = "color_r",
                        start_value = 0.32,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.19,
                        key_type = "tween",
                        node_id = "mid_0",
                        property_id = "color_g",
                        start_value = 0.3,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.3,
                        key_type = "tween",
                        node_id = "mid_0",
                        property_id = "color_b",
                        start_value = 0.4,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.32,
                        key_type = "tween",
                        node_id = "mid_0",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 0.2,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.3,
                        key_type = "tween",
                        node_id = "mid_0",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 0.19,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.4,
                        key_type = "tween",
                        node_id = "mid_0",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 0.3,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.2,
                        key_type = "tween",
                        node_id = "mid_1",
                        property_id = "color_r",
                        start_value = 0.32,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.19,
                        key_type = "tween",
                        node_id = "mid_1",
                        property_id = "color_g",
                        start_value = 0.3,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.3,
                        key_type = "tween",
                        node_id = "mid_1",
                        property_id = "color_b",
                        start_value = 0.4,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.32,
                        key_type = "tween",
                        node_id = "mid_1",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 0.2,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.3,
                        key_type = "tween",
                        node_id = "mid_1",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 0.19,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.4,
                        key_type = "tween",
                        node_id = "mid_1",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 0.3,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.55,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.34,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 0.55,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 0.34,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.55,
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.34,
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.7,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "color_r",
                        start_time = 0.7,
                        start_value = 0.55,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "color_g",
                        start_time = 0.7,
                        start_value = 0.34,
                    },
                    {
                        duration = 0.7,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "color_b",
                        start_time = 0.7,
                        start_value = 0.42,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "wind",
                animation_keys = {
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 132,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "size_y",
                        start_value = 110,
                    },
                    {
                        duration = 0.45,
                        easing = "outelastic",
                        end_value = 110,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "size_y",
                        start_time = 0.35,
                        start_value = 132,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.45,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "front_0",
                        property_id = "rotation_z",
                        start_time = 0.35,
                        start_value = 1.5,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 132,
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "size_y",
                        start_value = 110,
                    },
                    {
                        duration = 0.45,
                        easing = "outelastic",
                        end_value = 110,
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "size_y",
                        start_time = 0.35,
                        start_value = 132,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.45,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "front_1",
                        property_id = "rotation_z",
                        start_time = 0.35,
                        start_value = 1.5,
                    },
                },
                duration = 0.9,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/parallax/parallax.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
