return {
    data = {
        animations = {
            {
                animation_id = "fall",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "floor#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "floor#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "floor#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "piece_0#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "piece_0#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "piece_0#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "piece_1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "piece_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "piece_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "piece_3#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_3#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_3#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "piece_4#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "piece_4#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "piece_4#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_5#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_5#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "piece_5#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "piece_6#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "piece_6#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_6#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "piece_7#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_7#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_7#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "piece_8#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "piece_8#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "piece_8#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        end_value = -18,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                        start_time = 0.16,
                        start_value = -18,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        end_value = -18,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.085,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.245,
                        start_value = -18,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        end_value = -18,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.17,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.33,
                        start_value = -18,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        end_value = -18,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.255,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.41500000000000004,
                        start_value = -18,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        end_value = -18,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.34,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = -18,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        end_value = -18,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.42500000000000004,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.5850000000000001,
                        start_value = -18,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        end_value = -18,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.51,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.67,
                        start_value = -18,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        end_value = -18,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.5950000000000001,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.7550000000000001,
                        start_value = -18,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        end_value = -18,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_time = 0.68,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_time = 0.8400000000000001,
                        start_value = -18,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "rise",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "floor#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "floor#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "floor#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "piece_0#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "piece_0#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "piece_0#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "piece_1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "piece_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "piece_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "piece_3#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_3#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_3#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "piece_4#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "piece_4#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "piece_4#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_5#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_5#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "piece_5#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "piece_6#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "piece_6#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_6#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "piece_7#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_7#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_7#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "piece_8#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "piece_8#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "piece_8#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                        start_time = 0.6,
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                        start_time = 1,
                        start_value = 6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.525,
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.925,
                        start_value = 6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.44999999999999996,
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.85,
                        start_value = 6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.375,
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.775,
                        start_value = 6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.3,
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.7,
                        start_value = 6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.22499999999999998,
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.625,
                        start_value = 6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.15,
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.55,
                        start_value = 6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.075,
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.47500000000000003,
                        start_value = 6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = -76,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_value = -76,
                    },
                    {
                        duration = 0.4,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_time = 0.4,
                        start_value = 6,
                    },
                },
                duration = 1.5,
            },
            {
                animation_id = "wave",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.173,
                        key_type = "tween",
                        node_id = "floor#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.184,
                        key_type = "tween",
                        node_id = "floor#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.204,
                        key_type = "tween",
                        node_id = "floor#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "piece_0#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "piece_0#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "piece_0#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "piece_1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "piece_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "piece_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "piece_3#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_3#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_3#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "piece_4#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "piece_4#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "piece_4#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_5#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_5#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "piece_5#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "piece_6#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "piece_6#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_6#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "piece_7#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "piece_7#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "piece_7#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "piece_8#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "piece_8#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "piece_8#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.2,
                        easing = "inoutsine",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                        start_time = 0.2,
                        start_value = -14,
                    },
                    {
                        duration = 0.35,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_0",
                        property_id = "rotation_z",
                        start_time = 0.4,
                        start_value = 14,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.2,
                        easing = "inoutsine",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.26,
                        start_value = -14,
                    },
                    {
                        duration = 0.35,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_1",
                        property_id = "rotation_z",
                        start_time = 0.46,
                        start_value = 14,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.2,
                        easing = "inoutsine",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.32,
                        start_value = -14,
                    },
                    {
                        duration = 0.35,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_2",
                        property_id = "rotation_z",
                        start_time = 0.52,
                        start_value = 14,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.2,
                        easing = "inoutsine",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.38,
                        start_value = -14,
                    },
                    {
                        duration = 0.35,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_3",
                        property_id = "rotation_z",
                        start_time = 0.5800000000000001,
                        start_value = 14,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.24,
                    },
                    {
                        duration = 0.2,
                        easing = "inoutsine",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.44,
                        start_value = -14,
                    },
                    {
                        duration = 0.35,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_4",
                        property_id = "rotation_z",
                        start_time = 0.64,
                        start_value = 14,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.3,
                    },
                    {
                        duration = 0.2,
                        easing = "inoutsine",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = -14,
                    },
                    {
                        duration = 0.35,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_5",
                        property_id = "rotation_z",
                        start_time = 0.7,
                        start_value = 14,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.36,
                    },
                    {
                        duration = 0.2,
                        easing = "inoutsine",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.56,
                        start_value = -14,
                    },
                    {
                        duration = 0.35,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_6",
                        property_id = "rotation_z",
                        start_time = 0.76,
                        start_value = 14,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.42,
                    },
                    {
                        duration = 0.2,
                        easing = "inoutsine",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.62,
                        start_value = -14,
                    },
                    {
                        duration = 0.35,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_7",
                        property_id = "rotation_z",
                        start_time = 0.8200000000000001,
                        start_value = 14,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -14,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_time = 0.48,
                    },
                    {
                        duration = 0.2,
                        easing = "inoutsine",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_time = 0.6799999999999999,
                        start_value = -14,
                    },
                    {
                        duration = 0.35,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "piece_8",
                        property_id = "rotation_z",
                        start_time = 0.88,
                        start_value = 14,
                    },
                },
                duration = 1.4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/domino/domino.collection",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
