return {
    data = {
        animations = {
            {
                animation_id = "appear1",
                animation_keys = {
                    {
                        easing = "outsine",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_1/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_11/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_3/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_5/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_7/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_9/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_0/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_10/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_12/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_2/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_4/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_6/shape",
                        property_id = "position_x",
                    },
                    {
                        easing = "outsine",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_8/shape",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_6/shape",
                        property_id = "position_x",
                        start_value = 1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_5/shape",
                        property_id = "position_x",
                        start_time = 0.04,
                        start_value = -1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_7/shape",
                        property_id = "position_x",
                        start_time = 0.04,
                        start_value = -1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_4/shape",
                        property_id = "position_x",
                        start_time = 0.08,
                        start_value = 1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_8/shape",
                        property_id = "position_x",
                        start_time = 0.08,
                        start_value = 1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_3/shape",
                        property_id = "position_x",
                        start_time = 0.12,
                        start_value = -1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_9/shape",
                        property_id = "position_x",
                        start_time = 0.12,
                        start_value = -1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_10/shape",
                        property_id = "position_x",
                        start_time = 0.16,
                        start_value = 1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_2/shape",
                        property_id = "position_x",
                        start_time = 0.16,
                        start_value = 1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_1/shape",
                        property_id = "position_x",
                        start_time = 0.2,
                        start_value = -1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_11/shape",
                        property_id = "position_x",
                        start_time = 0.2,
                        start_value = -1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_0/shape",
                        property_id = "position_x",
                        start_time = 0.24,
                        start_value = 1900,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "stripe_12/shape",
                        property_id = "position_x",
                        start_time = 0.24,
                        start_value = 1900,
                    },
                },
                duration = 0.9,
            },
            {
                animation_id = "disappear1",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_6/shape",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_5/shape",
                        property_id = "position_x",
                        start_time = 0.04,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_7/shape",
                        property_id = "position_x",
                        start_time = 0.04,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_4/shape",
                        property_id = "position_x",
                        start_time = 0.08,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_8/shape",
                        property_id = "position_x",
                        start_time = 0.08,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_3/shape",
                        property_id = "position_x",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_9/shape",
                        property_id = "position_x",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_10/shape",
                        property_id = "position_x",
                        start_time = 0.16,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_2/shape",
                        property_id = "position_x",
                        start_time = 0.16,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_1/shape",
                        property_id = "position_x",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = 1900,
                        key_type = "tween",
                        node_id = "stripe_11/shape",
                        property_id = "position_x",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_0/shape",
                        property_id = "position_x",
                        start_time = 0.24,
                    },
                    {
                        duration = 0.5,
                        easing = "incubic",
                        end_value = -1900,
                        key_type = "tween",
                        node_id = "stripe_12/shape",
                        property_id = "position_x",
                        start_time = 0.24,
                    },
                },
                duration = 0.9,
            },
            {
                animation_id = "appear2",
                animation_keys = {
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_0/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_1/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_10/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_11/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_12/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_2/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_3/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_4/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_5/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_6/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_7/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_8/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "stripe_9/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_0/shape",
                        property_id = "scale_y",
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_1/shape",
                        property_id = "scale_y",
                        start_time = 0.03,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_2/shape",
                        property_id = "scale_y",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_3/shape",
                        property_id = "scale_y",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_4/shape",
                        property_id = "scale_y",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_5/shape",
                        property_id = "scale_y",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_6/shape",
                        property_id = "scale_y",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_7/shape",
                        property_id = "scale_y",
                        start_time = 0.21,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_8/shape",
                        property_id = "scale_y",
                        start_time = 0.24,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_9/shape",
                        property_id = "scale_y",
                        start_time = 0.27,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_10/shape",
                        property_id = "scale_y",
                        start_time = 0.3,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_11/shape",
                        property_id = "scale_y",
                        start_time = 0.33,
                    },
                    {
                        duration = 0.45,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stripe_12/shape",
                        property_id = "scale_y",
                        start_time = 0.36,
                    },
                },
                duration = 0.9,
            },
            {
                animation_id = "disappear2",
                animation_keys = {
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_12/shape",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_11/shape",
                        property_id = "scale_y",
                        start_time = 0.03,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_10/shape",
                        property_id = "scale_y",
                        start_time = 0.06,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_9/shape",
                        property_id = "scale_y",
                        start_time = 0.09,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_8/shape",
                        property_id = "scale_y",
                        start_time = 0.12,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_7/shape",
                        property_id = "scale_y",
                        start_time = 0.15,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_6/shape",
                        property_id = "scale_y",
                        start_time = 0.18,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_5/shape",
                        property_id = "scale_y",
                        start_time = 0.21,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_4/shape",
                        property_id = "scale_y",
                        start_time = 0.24,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_3/shape",
                        property_id = "scale_y",
                        start_time = 0.27,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_2/shape",
                        property_id = "scale_y",
                        start_time = 0.3,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_1/shape",
                        property_id = "scale_y",
                        start_time = 0.33,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        key_type = "tween",
                        node_id = "stripe_0/shape",
                        property_id = "scale_y",
                        start_time = 0.36,
                        start_value = 1,
                    },
                },
                duration = 0.9,
            },
            {
                animation_id = "together1",
                animation_keys = {
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "appear1",
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "disappear1",
                        start_time = 0.9,
                    },
                },
                duration = 1.8,
            },
            {
                animation_id = "together2",
                animation_keys = {
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "appear2",
                    },
                    {
                        duration = 0.9,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "disappear2",
                        start_time = 0.9,
                    },
                },
                duration = 1.8,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.01,
            },
            gui_path = "example/examples/transitions/transitions.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}