return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 1.4,
                        key_type = "tween",
                        node_id = "panthera#sprite",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 1.4,
                        key_type = "tween",
                        node_id = "panthera#sprite",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.19,
                        key_type = "tween",
                        node_id = "panthera#label",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.19,
                        key_type = "tween",
                        node_id = "panthera#label",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 2,
                        easing = "outsine",
                        end_value = 0.82,
                        key_type = "tween",
                        node_id = "panthera#label",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        data = "Hey!",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "panthera#label",
                        property_id = "text",
                        start_data = "Text",
                        start_time = 0.5,
                    },
                    {
                        data = "Text is",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "panthera#label",
                        property_id = "text",
                        start_data = "Hey!",
                        start_time = 1,
                    },
                    {
                        data = "example/ui_circle",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "panthera#sprite",
                        property_id = "texture",
                        start_data = "example/panthera",
                        start_time = 1,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "panthera#sprite",
                        property_id = "scale_x",
                        start_time = 1,
                        start_value = 1.4,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "panthera#sprite",
                        property_id = "scale_y",
                        start_time = 1,
                        start_value = 1.4,
                    },
                    {
                        data = "CHANING",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "panthera#label",
                        property_id = "text",
                        start_data = "Text is",
                        start_time = 2,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "panthera#label",
                        property_id = "color_b",
                        start_time = 2,
                        start_value = 0.19,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "panthera#label",
                        property_id = "color_g",
                        start_time = 2,
                        start_value = 0.19,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "panthera#label",
                        property_id = "color_r",
                        start_time = 2,
                        start_value = 0.82,
                    },
                },
                duration = 3,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
            {
                blend_mode = "alpha",
                clipping_mode = "none",
                clipping_visible = true,
                color_a = 1,
                color_b = 1,
                color_g = 1,
                color_r = 1,
                enabled = true,
                inherit_alpha = true,
                node_id = "panthera",
                node_index = 1,
                node_type = "box",
                pivot = "pivot_center",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_mode = "manual",
                size_x = 1,
                size_y = 1,
            },
            {
                blend_mode = "alpha",
                clipping_mode = "none",
                clipping_visible = true,
                color_a = 1,
                color_b = 1,
                color_g = 1,
                color_r = 1,
                enabled = true,
                fill_angle = 360,
                inherit_alpha = true,
                node_id = "panthera#sprite",
                node_index = 2,
                node_type = "box",
                outer_bounds = "ellipse",
                parent = "panthera",
                perimeter_vertices = 10,
                pivot = "pivot_center",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_mode = "auto",
                size_x = 128,
                size_y = 128,
                text_leading = 1,
                texture = "example/panthera",
                visible = true,
            },
            {
                blend_mode = "alpha",
                clipping_mode = "none",
                clipping_visible = true,
                color_a = 1,
                color_b = 1,
                color_g = 1,
                color_r = 1,
                enabled = true,
                fill_angle = 360,
                inherit_alpha = true,
                node_id = "panthera#label",
                node_index = 3,
                node_type = "text",
                outer_bounds = "ellipse",
                parent = "panthera",
                perimeter_vertices = 10,
                pivot = "pivot_center",
                position_y = 70,
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_mode = "manual",
                size_x = 128,
                size_y = 32,
                text = "Text",
                text_leading = 1,
                visible = true,
            },
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}