return {
    data = {
        animations = {
            {
                animation_id = "sine",
                animation_keys = {
                    {
                        duration = 1.4,
                        easing = "insine",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_in",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outsine",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_out",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutsine",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_inout",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outinsine",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_outin",
                        property_id = "position_x",
                        start_value = -300,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "quad",
                animation_keys = {
                    {
                        duration = 1.4,
                        easing = "inquad",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_in",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outquad",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_out",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutquad",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_inout",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outinquad",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_outin",
                        property_id = "position_x",
                        start_value = -300,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "cubic",
                animation_keys = {
                    {
                        duration = 1.4,
                        easing = "incubic",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_in",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outcubic",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_out",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutcubic",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_inout",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outincubic",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_outin",
                        property_id = "position_x",
                        start_value = -300,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "quart",
                animation_keys = {
                    {
                        duration = 1.4,
                        easing = "inquart",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_in",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outquart",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_out",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutquart",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_inout",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outinquart",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_outin",
                        property_id = "position_x",
                        start_value = -300,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "expo",
                animation_keys = {
                    {
                        duration = 1.4,
                        easing = "inexpo",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_in",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outexpo",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_out",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutexpo",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_inout",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outinexpo",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_outin",
                        property_id = "position_x",
                        start_value = -300,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "circ",
                animation_keys = {
                    {
                        duration = 1.4,
                        easing = "incirc",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_in",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outcirc",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_out",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutcirc",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_inout",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outincirc",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_outin",
                        property_id = "position_x",
                        start_value = -300,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "back",
                animation_keys = {
                    {
                        duration = 1.4,
                        easing = "inback",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_in",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outback",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_out",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutback",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_inout",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outinback",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_outin",
                        property_id = "position_x",
                        start_value = -300,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "elastic",
                animation_keys = {
                    {
                        duration = 1.4,
                        easing = "inelastic",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_in",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outelastic",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_out",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutelastic",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_inout",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outinelastic",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_outin",
                        property_id = "position_x",
                        start_value = -300,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "bounce",
                animation_keys = {
                    {
                        duration = 1.4,
                        easing = "inbounce",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_in",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outbounce",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_out",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutbounce",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_inout",
                        property_id = "position_x",
                        start_value = -300,
                    },
                    {
                        duration = 1.4,
                        easing = "outinbounce",
                        end_value = 340,
                        key_type = "tween",
                        node_id = "dot_outin",
                        property_id = "position_x",
                        start_value = -300,
                    },
                },
                duration = 1.4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/easings/easings.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
