return {
    data = {
        animations = {
            {
                animation_id = "combo",
                animation_keys = {
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 560,
                        key_type = "tween",
                        node_id = "ring_0",
                        property_id = "size_x",
                        start_value = 120,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 560,
                        key_type = "tween",
                        node_id = "ring_0",
                        property_id = "size_y",
                        start_value = 120,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "ring_0",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "ring_0",
                        property_id = "color_a",
                        start_time = 0.1,
                        start_value = 0.7,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 560,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "size_x",
                        start_time = 0.12,
                        start_value = 120,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 560,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "size_y",
                        start_time = 0.12,
                        start_value = 120,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "color_a",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "color_a",
                        start_time = 0.22,
                        start_value = 0.7,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 560,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "size_x",
                        start_time = 0.24,
                        start_value = 120,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 560,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "size_y",
                        start_time = 0.24,
                        start_value = 120,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "color_a",
                        start_time = 0.24,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "color_a",
                        start_time = 0.33999999999999997,
                        start_value = 0.7,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        data = "x2",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_combo",
                        property_id = "text",
                        start_data = "x2",
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 1.9,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_x",
                        start_value = 0.5,
                    },
                    {
                        duration = 0.45,
                        easing = "outelastic",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_x",
                        start_time = 0.25,
                        start_value = 1.9,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 1.9,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_y",
                        start_value = 0.5,
                    },
                    {
                        duration = 0.45,
                        easing = "outelastic",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_y",
                        start_time = 0.25,
                        start_value = 1.9,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_0",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_1",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_2",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_3",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_4",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_5",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_6",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_7",
                        property_id = "color_a",
                    },
                },
                duration = 1.1,
            },
            {
                animation_id = "crit",
                animation_keys = {
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "ring_0",
                        property_id = "size_x",
                        start_value = 120,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "ring_0",
                        property_id = "size_y",
                        start_value = 120,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "ring_0",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "ring_0",
                        property_id = "color_a",
                        start_time = 0.1,
                        start_value = 0.7,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "size_x",
                        start_time = 0.1,
                        start_value = 120,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "size_y",
                        start_time = 0.1,
                        start_value = 120,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "color_a",
                        start_time = 0.1,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "color_a",
                        start_time = 0.2,
                        start_value = 0.7,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "size_x",
                        start_time = 0.2,
                        start_value = 120,
                    },
                    {
                        duration = 0.6,
                        easing = "outcubic",
                        end_value = 760,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "size_y",
                        start_time = 0.2,
                        start_value = 120,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "color_a",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "color_a",
                        start_time = 0.30000000000000004,
                        start_value = 0.7,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_r",
                        start_time = 0.6,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_g",
                        start_time = 0.6,
                        start_value = 0.502,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_b",
                        start_time = 0.6,
                        start_value = 0.6,
                    },
                    {
                        data = "x9",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_combo",
                        property_id = "text",
                        start_data = "x2",
                    },
                    {
                        data = "x2",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_combo",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.9,
                    },
                    {
                        duration = 0.2,
                        easing = "outback",
                        end_value = 2.3,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_x",
                        start_value = 0.3,
                    },
                    {
                        duration = 0.5,
                        easing = "outelastic",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_x",
                        start_time = 0.2,
                        start_value = 2.3,
                    },
                    {
                        duration = 0.2,
                        easing = "outback",
                        end_value = 2.3,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_y",
                        start_value = 0.3,
                    },
                    {
                        duration = 0.5,
                        easing = "outelastic",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_y",
                        start_time = 0.2,
                        start_value = 2.3,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "spark_0",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 330,
                        key_type = "tween",
                        node_id = "spark_0",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "spark_0",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "spark_0",
                        property_id = "color_a",
                        start_time = 0.3,
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "spark_1",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 233.3452377915607,
                        key_type = "tween",
                        node_id = "spark_1",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 233.34523779156066,
                        key_type = "tween",
                        node_id = "spark_1",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "spark_1",
                        property_id = "color_a",
                        start_time = 0.3,
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "spark_2",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 2.0206672185931328e-14,
                        key_type = "tween",
                        node_id = "spark_2",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 330,
                        key_type = "tween",
                        node_id = "spark_2",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "spark_2",
                        property_id = "color_a",
                        start_time = 0.3,
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "spark_3",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = -233.34523779156066,
                        key_type = "tween",
                        node_id = "spark_3",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 233.3452377915607,
                        key_type = "tween",
                        node_id = "spark_3",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "spark_3",
                        property_id = "color_a",
                        start_time = 0.3,
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "spark_4",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = -330,
                        key_type = "tween",
                        node_id = "spark_4",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 4.0413344371862656e-14,
                        key_type = "tween",
                        node_id = "spark_4",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "spark_4",
                        property_id = "color_a",
                        start_time = 0.3,
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "spark_5",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = -233.34523779156075,
                        key_type = "tween",
                        node_id = "spark_5",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = -233.34523779156066,
                        key_type = "tween",
                        node_id = "spark_5",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "spark_5",
                        property_id = "color_a",
                        start_time = 0.3,
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "spark_6",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = -6.062001655779397e-14,
                        key_type = "tween",
                        node_id = "spark_6",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = -330,
                        key_type = "tween",
                        node_id = "spark_6",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "spark_6",
                        property_id = "color_a",
                        start_time = 0.3,
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "spark_7",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = 233.34523779156063,
                        key_type = "tween",
                        node_id = "spark_7",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.55,
                        easing = "outcubic",
                        end_value = -233.34523779156075,
                        key_type = "tween",
                        node_id = "spark_7",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "spark_7",
                        property_id = "color_a",
                        start_time = 0.3,
                        start_value = 1,
                    },
                },
                duration = 1.3,
            },
            {
                animation_id = "fade",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        data = "x2",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_combo",
                        property_id = "text",
                        start_data = "x2",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_x",
                        start_value = 1.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1.6,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "scale_y",
                        start_value = 1.6,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "text_label",
                        property_id = "color_a",
                        start_time = 0.1,
                        start_value = 1,
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = 130,
                        key_type = "tween",
                        node_id = "text_combo",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.7,
                        easing = "outcubic",
                        end_value = -60,
                        key_type = "tween",
                        node_id = "text_label",
                        property_id = "position_y",
                        start_value = -140,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "ring_0",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_0",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_1",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_2",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_3",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_4",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_5",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_6",
                        property_id = "color_a",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "spark_7",
                        property_id = "color_a",
                    },
                },
                duration = 0.9,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/combo_pop/combo_pop.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
