return {
    data = {
        animations = {
            {
                animation_id = "text",
                animation_keys = {
                    {
                        data = "Panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "caption#label",
                        property_id = "text",
                        start_data = "Game Object",
                    },
                    {
                        data = "animates",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "caption#label",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.5,
                    },
                    {
                        data = "game objects",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "caption#label",
                        property_id = "text",
                        start_data = "",
                        start_time = 1,
                    },
                    {
                        data = "and components",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "caption#label",
                        property_id = "text",
                        start_data = "",
                        start_time = 1.5,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_time = 0.12,
                        start_value = 1.25,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_time = 0.12,
                        start_value = 1.25,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_time = 0.62,
                        start_value = 1.25,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_time = 0.62,
                        start_value = 1.25,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_time = 1,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_time = 1.12,
                        start_value = 1.25,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_time = 1,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_time = 1.12,
                        start_value = 1.25,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_time = 1.5,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_time = 1.62,
                        start_value = 1.25,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.25,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_time = 1.5,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_time = 1.62,
                        start_value = 1.25,
                    },
                },
                duration = 2,
            },
            {
                animation_id = "color",
                animation_keys = {
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "caption#label",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "caption#label",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "caption#label",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "caption#label",
                        property_id = "color_r",
                        start_time = 0.6,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "caption#label",
                        property_id = "color_g",
                        start_time = 0.6,
                        start_value = 0.502,
                    },
                    {
                        duration = 0.6,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "caption#label",
                        property_id = "color_b",
                        start_time = 0.6,
                        start_value = 0.902,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption#label",
                        property_id = "outline_a",
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "caption#label",
                        property_id = "outline_a",
                        start_time = 0.8,
                        start_value = 1,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "pop",
                animation_keys = {
                    {
                        duration = 0.35,
                        easing = "outback",
                        end_value = 60,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.55,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "position_y",
                        start_time = 0.35,
                        start_value = 60,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.6,
                        easing = "outelastic",
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "rotation_z",
                        start_time = 0.3,
                        start_value = -10,
                    },
                    {
                        duration = 0.35,
                        easing = "outback",
                        end_value = 1.35,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.55,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_x",
                        start_time = 0.35,
                        start_value = 1.35,
                    },
                    {
                        duration = 0.35,
                        easing = "outback",
                        end_value = 1.35,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.55,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "caption",
                        property_id = "scale_y",
                        start_time = 0.35,
                        start_value = 1.35,
                    },
                },
                duration = 0.9,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example2/examples/go_label/caption.go",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
