return {
    data = {
        animations = {
            {
                animation_id = "swap",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "ring_1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "ring_1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "ring_1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "ring_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "ring_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "ring_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.4,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "core",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.7,
                        easing = "inoutsine",
                        end_value = 220,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "position_x",
                        start_value = -220,
                    },
                    {
                        duration = 0.7,
                        easing = "inoutsine",
                        end_value = -220,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "position_x",
                        start_time = 0.7,
                        start_value = 220,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 160,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.6,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 160,
                    },
                    {
                        duration = 0.7,
                        easing = "inoutsine",
                        end_value = -220,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "position_x",
                        start_value = 220,
                    },
                    {
                        duration = 0.7,
                        easing = "inoutsine",
                        end_value = 220,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "position_x",
                        start_time = 0.7,
                        start_value = -220,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 160,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "position_y",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.6,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "position_y",
                        start_time = 0.7,
                        start_value = 160,
                    },
                },
                duration = 1.5,
            },
            {
                animation_id = "collapse",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "ring_1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "ring_1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "ring_1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "scale_x",
                        start_value = 3,
                    },
                    {
                        duration = 0.55,
                        easing = "outback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "scale_x",
                        start_time = 0.45,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "scale_y",
                        start_value = 3,
                    },
                    {
                        duration = 0.55,
                        easing = "outback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "scale_y",
                        start_time = 0.45,
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "ring_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "ring_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "ring_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "scale_x",
                        start_value = 3,
                    },
                    {
                        duration = 0.55,
                        easing = "outback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "scale_x",
                        start_time = 0.45,
                        start_value = 1,
                    },
                    {
                        duration = 0.45,
                        easing = "inback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "scale_y",
                        start_value = 3,
                    },
                    {
                        duration = 0.55,
                        easing = "outback",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "scale_y",
                        start_time = 0.45,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 3.4,
                        key_type = "tween",
                        node_id = "core",
                        property_id = "scale_x",
                        start_time = 0.2,
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "core",
                        property_id = "scale_x",
                        start_time = 0.6,
                        start_value = 3.4,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 3.4,
                        key_type = "tween",
                        node_id = "core",
                        property_id = "scale_y",
                        start_time = 0.2,
                        start_value = 2,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "core",
                        property_id = "scale_y",
                        start_time = 0.6,
                        start_value = 3.4,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "charge",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_r",
                        start_time = 0.5,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_g",
                        start_time = 0.5,
                        start_value = 0.502,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "core#sprite",
                        property_id = "color_b",
                        start_time = 0.5,
                        start_value = 0.902,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "ring_1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "ring_1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "ring_1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "inoutcubic",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "ring_1",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "ring_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "ring_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "ring_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "inoutcubic",
                        end_value = 720,
                        key_type = "tween",
                        node_id = "ring_2",
                        property_id = "rotation_z",
                    },
                },
                duration = 1.2,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example2/examples/nested_collection/satellite.collection",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
