return {
    data = {
        animations = {
            {
                animation_id = "flip_x",
                animation_keys = {
                    {
                        duration = 0.25,
                        easing = "incubic",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_time = 0.25,
                    },
                    {
                        duration = 0.25,
                        easing = "incubic",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_time = 0.75,
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_time = 1,
                    },
                    {
                        data = "PANTHERA",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_face",
                        property_id = "text",
                        start_data = "PANTHERA",
                    },
                    {
                        data = "RUNTIME",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_face",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.25,
                    },
                    {
                        data = "PANTHERA",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_face",
                        property_id = "text",
                        start_data = "",
                        start_time = 1,
                    },
                    {
                        data = "panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "icon",
                        property_id = "texture",
                        start_data = "panthera",
                    },
                    {
                        data = "icon_check",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "icon",
                        property_id = "texture",
                        start_data = "",
                        start_time = 0.25,
                    },
                    {
                        data = "panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "icon",
                        property_id = "texture",
                        start_data = "",
                        start_time = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_r",
                        start_time = 0.25,
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_g",
                        start_time = 0.25,
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_b",
                        start_time = 0.25,
                        start_value = 0.333,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_r",
                        start_time = 1,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_g",
                        start_time = 1,
                        start_value = 0.502,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_b",
                        start_time = 1,
                        start_value = 0.902,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "position_x",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "position_y",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "position_x",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 1.06,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_time = 0.25,
                        start_value = 1.06,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 1.06,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_time = 0.75,
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_time = 1,
                        start_value = 1.06,
                    },
                    {
                        duration = 0.25,
                        easing = "incubic",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "size_x",
                        start_value = 320,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "size_x",
                        start_time = 0.25,
                        start_value = 120,
                    },
                    {
                        duration = 0.25,
                        easing = "incubic",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "size_x",
                        start_time = 0.75,
                        start_value = 320,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "size_x",
                        start_time = 1,
                        start_value = 120,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "flip_y",
                animation_keys = {
                    {
                        duration = 0.25,
                        easing = "incubic",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_time = 0.25,
                    },
                    {
                        duration = 0.25,
                        easing = "incubic",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_time = 0.75,
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_time = 1,
                    },
                    {
                        data = "PANTHERA",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_face",
                        property_id = "text",
                        start_data = "PANTHERA",
                    },
                    {
                        data = "RUNTIME",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_face",
                        property_id = "text",
                        start_data = "",
                        start_time = 0.25,
                    },
                    {
                        data = "PANTHERA",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_face",
                        property_id = "text",
                        start_data = "",
                        start_time = 1,
                    },
                    {
                        data = "panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "icon",
                        property_id = "texture",
                        start_data = "panthera",
                    },
                    {
                        data = "icon_check",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "icon",
                        property_id = "texture",
                        start_data = "",
                        start_time = 0.25,
                    },
                    {
                        data = "panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "icon",
                        property_id = "texture",
                        start_data = "",
                        start_time = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_r",
                        start_time = 0.25,
                        start_value = 0.894,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_g",
                        start_time = 0.25,
                        start_value = 0.506,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_b",
                        start_time = 0.25,
                        start_value = 0.333,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_r",
                        start_time = 1,
                        start_value = 0.6,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_g",
                        start_time = 1,
                        start_value = 0.502,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_b",
                        start_time = 1,
                        start_value = 0.902,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "position_x",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "position_y",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "position_x",
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 1.06,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_time = 0.25,
                        start_value = 1.06,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 1.06,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_time = 0.75,
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_time = 1,
                        start_value = 1.06,
                    },
                    {
                        duration = 0.25,
                        easing = "incubic",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "size_x",
                        start_value = 320,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "size_x",
                        start_time = 0.25,
                        start_value = 120,
                    },
                    {
                        duration = 0.25,
                        easing = "incubic",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "size_x",
                        start_time = 0.75,
                        start_value = 320,
                    },
                    {
                        duration = 0.3,
                        easing = "outcubic",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "size_x",
                        start_time = 1,
                        start_value = 120,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "deal",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        data = "PANTHERA",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "text_face",
                        property_id = "text",
                        start_data = "PANTHERA",
                    },
                    {
                        data = "panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "icon",
                        property_id = "texture",
                        start_data = "panthera",
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "position_x",
                        start_value = -700,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "position_y",
                        start_value = 260,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "card",
                        property_id = "rotation_z",
                        start_value = -35,
                    },
                    {
                        duration = 0.5,
                        easing = "outcubic",
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "position_x",
                        start_value = -700,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 1.08,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_x",
                        start_time = 0.4,
                        start_value = 1.08,
                    },
                    {
                        duration = 0.4,
                        easing = "outcubic",
                        end_value = 1.08,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card",
                        property_id = "scale_y",
                        start_time = 0.4,
                        start_value = 1.08,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/card_flip/card_flip.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
