return {
    data = {
        animations = {
            {
                animation_id = "wave",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 170,
                        key_type = "tween",
                        node_id = "scene_dot_1",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.4,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "scene_dot_1",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = 170,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 170,
                        key_type = "tween",
                        node_id = "scene_dot_2",
                        property_id = "position_y",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.4,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "scene_dot_2",
                        property_id = "position_y",
                        start_time = 0.39,
                        start_value = 170,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 170,
                        key_type = "tween",
                        node_id = "scene_dot_3",
                        property_id = "position_y",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.4,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "scene_dot_3",
                        property_id = "position_y",
                        start_time = 0.48,
                        start_value = 170,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 170,
                        key_type = "tween",
                        node_id = "scene_dot_4",
                        property_id = "position_y",
                        start_time = 0.27,
                    },
                    {
                        duration = 0.4,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "scene_dot_4",
                        property_id = "position_y",
                        start_time = 0.5700000000000001,
                        start_value = 170,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 170,
                        key_type = "tween",
                        node_id = "scene_dot_5",
                        property_id = "position_y",
                        start_time = 0.36,
                    },
                    {
                        duration = 0.4,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "scene_dot_5",
                        property_id = "position_y",
                        start_time = 0.6599999999999999,
                        start_value = 170,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "ripple",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_1",
                        property_id = "scale_x",
                        start_time = 0.16,
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_1",
                        property_id = "scale_x",
                        start_time = 0.41000000000000003,
                        start_value = 3.2,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_1",
                        property_id = "scale_y",
                        start_time = 0.16,
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_1",
                        property_id = "scale_y",
                        start_time = 0.41000000000000003,
                        start_value = 3.2,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_2",
                        property_id = "scale_x",
                        start_time = 0.08,
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_2",
                        property_id = "scale_x",
                        start_time = 0.33,
                        start_value = 3.2,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_2",
                        property_id = "scale_y",
                        start_time = 0.08,
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_2",
                        property_id = "scale_y",
                        start_time = 0.33,
                        start_value = 3.2,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_3",
                        property_id = "scale_x",
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_3",
                        property_id = "scale_x",
                        start_time = 0.25,
                        start_value = 3.2,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_3",
                        property_id = "scale_y",
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_3",
                        property_id = "scale_y",
                        start_time = 0.25,
                        start_value = 3.2,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_4",
                        property_id = "scale_x",
                        start_time = 0.08,
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_4",
                        property_id = "scale_x",
                        start_time = 0.33,
                        start_value = 3.2,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_4",
                        property_id = "scale_y",
                        start_time = 0.08,
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_4",
                        property_id = "scale_y",
                        start_time = 0.33,
                        start_value = 3.2,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_5",
                        property_id = "scale_x",
                        start_time = 0.16,
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_5",
                        property_id = "scale_x",
                        start_time = 0.41000000000000003,
                        start_value = 3.2,
                    },
                    {
                        duration = 0.25,
                        easing = "outback",
                        end_value = 3.2,
                        key_type = "tween",
                        node_id = "scene_dot_5",
                        property_id = "scale_y",
                        start_time = 0.16,
                        start_value = 2,
                    },
                    {
                        duration = 0.45,
                        easing = "inoutback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "scene_dot_5",
                        property_id = "scale_y",
                        start_time = 0.41000000000000003,
                        start_value = 3.2,
                    },
                },
                duration = 1.1,
            },
            {
                animation_id = "shift",
                animation_keys = {
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_r",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_g",
                        start_value = 0.502,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_b",
                        start_value = 0.902,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_r",
                        start_time = 0.4,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_g",
                        start_time = 0.4,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "scene_dot_1#sprite",
                        property_id = "color_b",
                        start_time = 0.4,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.8,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "scene_dot_1",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_r",
                        start_value = 0.8,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_g",
                        start_value = 0.502,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_b",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_r",
                        start_time = 0.46,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_g",
                        start_time = 0.46,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_2#sprite",
                        property_id = "color_b",
                        start_time = 0.46,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.8,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "scene_dot_2",
                        property_id = "rotation_z",
                        start_time = 0.06,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_r",
                        start_value = 0.894,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_g",
                        start_value = 0.506,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_b",
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_r",
                        start_time = 0.52,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_g",
                        start_time = 0.52,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "scene_dot_3#sprite",
                        property_id = "color_b",
                        start_time = 0.52,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.8,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "scene_dot_3",
                        property_id = "rotation_z",
                        start_time = 0.12,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_r",
                        start_value = 0.42,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_g",
                        start_value = 0.75,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_b",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_r",
                        start_time = 0.5800000000000001,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_g",
                        start_time = 0.5800000000000001,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_4#sprite",
                        property_id = "color_b",
                        start_time = 0.5800000000000001,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.8,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "scene_dot_4",
                        property_id = "rotation_z",
                        start_time = 0.18,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_r",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_g",
                        start_value = 0.502,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_b",
                        start_value = 0.902,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_r",
                        start_time = 0.64,
                        start_value = 0.42,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_g",
                        start_time = 0.64,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "scene_dot_5#sprite",
                        property_id = "color_b",
                        start_time = 0.64,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.8,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "scene_dot_5",
                        property_id = "rotation_z",
                        start_time = 0.24,
                    },
                },
                duration = 1.3,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example2/examples/scene_objects/dot.go",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
