return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = -125,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_y",
                        start_value = -55,
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 20,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 365,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_x",
                        start_value = 245,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = -55,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_y",
                        start_time = 0.34,
                        start_value = 5,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_y",
                        start_time = 0.34,
                        start_value = 20,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "rotation_z",
                        start_time = 0.34,
                        start_value = 15,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "rotation_z",
                        start_time = 0.34,
                        start_value = -15,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_x",
                        start_time = 0.34,
                        start_value = -125,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 245,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_x",
                        start_time = 0.34,
                        start_value = 365,
                    },
                    {
                        data = "up",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "card_1",
                        property_id = "layer",
                        start_time = 0.36,
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "rotation_z",
                        start_time = 1.11,
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_y",
                        start_time = 1.11,
                        start_value = -55,
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 365,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_x",
                        start_time = 1.11,
                        start_value = 245,
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = -125,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_x",
                        start_time = 1.19,
                        start_value = 30,
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "rotation_z",
                        start_time = 1.19,
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 20,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_y",
                        start_time = 1.19,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = -55,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_y",
                        start_time = 1.45,
                        start_value = 5,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "rotation_z",
                        start_time = 1.45,
                        start_value = -15,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 245,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_x",
                        start_time = 1.45,
                        start_value = 365,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_y",
                        start_time = 1.53,
                        start_value = 20,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "rotation_z",
                        start_time = 1.53,
                        start_value = 15,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_x",
                        start_time = 1.53,
                        start_value = -125,
                    },
                    {
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "card_1",
                        property_id = "layer",
                        start_data = "up",
                        start_time = 1.54,
                    },
                },
                duration = 2,
            },
            {
                animation_id = "asd",
                animation_keys = {
                },
                duration = 1,
            },
            {
                animation_id = "spin",
                animation_keys = {
                    {
                        easing = "outsine",
                        end_value = -200,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_x",
                    },
                    {
                        data = "up",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "card_1",
                        property_id = "layer",
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_y",
                        start_value = -55,
                    },
                    {
                        easing = "outsine",
                        end_value = 200,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_x",
                        start_value = 245,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = -150,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_x",
                        start_value = -200,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_x",
                        start_value = 200,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 150,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = -200,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_x",
                        start_time = 0.5,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = -150,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 150,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 200,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_x",
                        start_time = 0.5,
                    },
                    {
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "card_1",
                        property_id = "layer",
                        start_data = "up",
                        start_time = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = -150,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_y",
                        start_time = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_x",
                        start_time = 1,
                        start_value = 200,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_x",
                        start_time = 1,
                        start_value = -200,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "scale_x",
                        start_time = 1,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "scale_y",
                        start_time = 1,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "scale_x",
                        start_time = 1,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "scale_y",
                        start_time = 1,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        end_value = 155,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_y",
                        start_time = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = -200,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_x",
                        start_time = 1.5,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "position_y",
                        start_time = 1.5,
                        start_value = 155,
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_y",
                        start_time = 1.5,
                        start_value = -150,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "scale_x",
                        start_time = 1.5,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card_1",
                        property_id = "scale_y",
                        start_time = 1.5,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "scale_x",
                        start_time = 1.5,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "scale_y",
                        start_time = 1.5,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 200,
                        key_type = "tween",
                        node_id = "card_2",
                        property_id = "position_x",
                        start_time = 1.5,
                    },
                },
                duration = 2,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "example/test_layer/test_layer.gui",
            layers = {
                {
                    color = "73E84C",
                    name = "up",
                },
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}