return {
    data = {
        animations = {
            {
                animation_id = "move",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 300,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -300,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "position_x",
                        start_time = 0.5,
                        start_value = 300,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "position_x",
                        start_time = 1,
                        start_value = -300,
                    },
                    {
                        duration = 0.45,
                        easing = "outsine",
                        end_value = 140,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.45,
                        easing = "inoutsine",
                        end_value = -140,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "position_y",
                        start_time = 0.45,
                        start_value = 140,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "position_y",
                        start_time = 0.9,
                        start_value = -140,
                    },
                },
                duration = 1.4,
            },
            {
                animation_id = "spin",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 1.2,
                        easing = "inoutback",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.6,
                        easing = "outback",
                        end_value = 1.8,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_time = 0.6,
                        start_value = 1.8,
                    },
                    {
                        duration = 0.6,
                        easing = "outback",
                        end_value = 1.8,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_time = 0.6,
                        start_value = 1.8,
                    },
                },
                duration = 1.2,
            },
            {
                animation_id = "tint",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_r",
                        start_value = 0.722,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_g",
                        start_value = 0.741,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_b",
                        start_value = 0.761,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_r",
                        start_time = 0.5,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_g",
                        start_time = 0.5,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_b",
                        start_time = 0.5,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_r",
                        start_time = 1,
                        start_value = 0.6,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_g",
                        start_time = 1,
                        start_value = 0.502,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_b",
                        start_time = 1,
                        start_value = 0.902,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.2,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_a",
                        start_time = 0.4,
                        start_value = 0.2,
                    },
                },
                duration = 1.5,
            },
            {
                animation_id = "flipbook",
                animation_keys = {
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.722,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_r",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.741,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0,
                        easing = "linear",
                        end_value = 0.761,
                        key_type = "tween",
                        node_id = "hero#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        data = "panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "hero#sprite",
                        property_id = "texture",
                        start_data = "panthera",
                    },
                    {
                        data = "ui_circle_64",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "hero#sprite",
                        property_id = "texture",
                        start_data = "",
                        start_time = 0.4,
                    },
                    {
                        data = "icon_check",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "hero#sprite",
                        property_id = "texture",
                        start_data = "",
                        start_time = 0.8,
                    },
                    {
                        data = "panthera",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "hero#sprite",
                        property_id = "texture",
                        start_data = "",
                        start_time = 1.2,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_time = 0.12,
                        start_value = 1.5,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_time = 0.4,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_time = 0.52,
                        start_value = 1.5,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_time = 0.8,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_time = 0.92,
                        start_value = 1.5,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_time = 1.2,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_x",
                        start_time = 1.3199999999999998,
                        start_value = 1.5,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_time = 0.12,
                        start_value = 1.5,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_time = 0.4,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_time = 0.52,
                        start_value = 1.5,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_time = 0.8,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_time = 0.92,
                        start_value = 1.5,
                    },
                    {
                        duration = 0.12,
                        easing = "outquad",
                        end_value = 1.5,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_time = 1.2,
                        start_value = 1,
                    },
                    {
                        duration = 0.28,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "hero",
                        property_id = "scale_y",
                        start_time = 1.3199999999999998,
                        start_value = 1.5,
                    },
                },
                duration = 1.6,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/go_sprite/hero.go",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
