return {
    data = {
        animations = {
            {
                animation_id = "spotlight",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = -120,
                        key_type = "tween",
                        node_id = "group",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "group",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "position_x",
                    },
                    {
                        duration = 1,
                        easing = "inoutsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "group",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = -120,
                    },
                    {
                        duration = 1,
                        easing = "inoutsine",
                        end_value = -120,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 120,
                    },
                    {
                        duration = 0.8,
                        easing = "inoutsine",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "group",
                        property_id = "position_x",
                        start_time = 0.6,
                        start_value = -320,
                    },
                    {
                        duration = 0.8,
                        easing = "inoutsine",
                        end_value = -320,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "position_x",
                        start_time = 0.6,
                        start_value = 320,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "group",
                        property_id = "position_x",
                        start_time = 1.4,
                        start_value = 320,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "position_x",
                        start_time = 1.4,
                        start_value = -320,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "group",
                        property_id = "position_y",
                        start_time = 1.5,
                        start_value = 120,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "position_y",
                        start_time = 1.5,
                        start_value = -120,
                    },
                },
                duration = 2,
            },
            {
                animation_id = "iris",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "inoutcubic",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_x",
                        start_value = 320,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutcubic",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_y",
                        start_value = 320,
                    },
                    {
                        duration = 0.6,
                        easing = "outback",
                        end_value = 700,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_x",
                        start_time = 0.5,
                        start_value = 40,
                    },
                    {
                        duration = 0.6,
                        easing = "outback",
                        end_value = 700,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_y",
                        start_time = 0.5,
                        start_value = 40,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutcubic",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_x",
                        start_time = 1.1,
                        start_value = 700,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutcubic",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_y",
                        start_time = 1.1,
                        start_value = 700,
                    },
                },
                duration = 1.6,
            },
            {
                animation_id = "invert",
                animation_keys = {
                    {
                        data = "false",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "mask",
                        property_id = "clipping_inverted",
                        start_data = "false",
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 220,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_x",
                        start_value = 320,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 220,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_y",
                        start_value = 320,
                    },
                    {
                        data = "true",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "mask",
                        property_id = "clipping_inverted",
                        start_data = "false",
                        start_time = 0.5,
                    },
                    {
                        duration = 0.7,
                        easing = "inoutsine",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "rotation_z",
                        start_time = 0.5,
                    },
                    {
                        data = "false",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "mask",
                        property_id = "clipping_inverted",
                        start_data = "true",
                        start_time = 1.2,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_x",
                        start_time = 1.2,
                        start_value = 220,
                    },
                    {
                        duration = 0.5,
                        easing = "outback",
                        end_value = 320,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "size_y",
                        start_time = 1.2,
                        start_value = 220,
                    },
                    {
                        duration = 0.5,
                        easing = "inoutsine",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "mask",
                        property_id = "rotation_z",
                        start_time = 1.2,
                        start_value = 180,
                    },
                },
                duration = 1.8,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/clipping/clipping.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}