return {
    data = {
        animations = {
            {
                animation_id = "bounce",
                animation_keys = {
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "box_left",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.35,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "box_left",
                        property_id = "position_y",
                        start_time = 0.25,
                        start_value = 120,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "box_center",
                        property_id = "position_y",
                        start_time = 0.1,
                    },
                    {
                        duration = 0.35,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "box_center",
                        property_id = "position_y",
                        start_time = 0.35,
                        start_value = 120,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 120,
                        key_type = "tween",
                        node_id = "box_right",
                        property_id = "position_y",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.35,
                        easing = "outbounce",
                        key_type = "tween",
                        node_id = "box_right",
                        property_id = "position_y",
                        start_time = 0.45,
                        start_value = 120,
                    },
                },
                duration = 0.8,
            },
            {
                animation_id = "flash",
                animation_keys = {
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "box_left",
                        property_id = "color_r",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "box_left",
                        property_id = "color_r",
                        start_time = 0.2,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "box_left",
                        property_id = "color_g",
                        start_value = 0.502,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "box_left",
                        property_id = "color_g",
                        start_time = 0.2,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "box_left",
                        property_id = "color_b",
                        start_value = 0.902,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 0.902,
                        key_type = "tween",
                        node_id = "box_left",
                        property_id = "color_b",
                        start_time = 0.2,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "box_center",
                        property_id = "color_r",
                        start_value = 0.8,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "box_center",
                        property_id = "color_r",
                        start_time = 0.2,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "box_center",
                        property_id = "color_g",
                        start_value = 0.502,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 0.502,
                        key_type = "tween",
                        node_id = "box_center",
                        property_id = "color_g",
                        start_time = 0.2,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "box_center",
                        property_id = "color_b",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "box_center",
                        property_id = "color_b",
                        start_time = 0.2,
                        start_value = 0.333,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.894,
                        key_type = "tween",
                        node_id = "box_right",
                        property_id = "color_r",
                        start_value = 0.42,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 0.42,
                        key_type = "tween",
                        node_id = "box_right",
                        property_id = "color_r",
                        start_time = 0.2,
                        start_value = 0.894,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.506,
                        key_type = "tween",
                        node_id = "box_right",
                        property_id = "color_g",
                        start_value = 0.75,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "box_right",
                        property_id = "color_g",
                        start_time = 0.2,
                        start_value = 0.506,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 0.333,
                        key_type = "tween",
                        node_id = "box_right",
                        property_id = "color_b",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "box_right",
                        property_id = "color_b",
                        start_time = 0.2,
                        start_value = 0.333,
                    },
                },
                duration = 0.5,
            },
            {
                animation_id = "spin",
                animation_keys = {
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "box_left",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "box_center",
                        property_id = "rotation_z",
                        start_time = 0.08,
                    },
                    {
                        duration = 0.6,
                        easing = "inoutcubic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "box_right",
                        property_id = "rotation_z",
                        start_time = 0.16,
                    },
                },
                duration = 0.8,
            },
            {
                animation_id = "sequence",
                animation_keys = {
                    {
                        duration = 0.8,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "bounce",
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "flash",
                        start_time = 0.8,
                    },
                    {
                        duration = 0.8,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "spin",
                        start_time = 1.3,
                    },
                },
                duration = 2.1,
            },
            {
                animation_id = "chorus",
                animation_keys = {
                    {
                        duration = 0.8,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "bounce",
                    },
                    {
                        duration = 0.5,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "flash",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.8,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "spin",
                        start_time = 0.25,
                    },
                },
                duration = 1.1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
                time = 0.1,
            },
            gui_path = "example/examples/nested_animations/nested_animations.gui",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
